### ISSUE TITLE
Bylines missing on articles

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#1001]
Apparently this was happening:

![image](https://user-images.githubusercontent.com/5193330/32478124-b6ef7d84-c337-11e7-8b81-c40faa6898e7.png)

And this is because Article instances don't have a joined_bylines method or anything of that sort.

I wrote a method in the article cell that essentially does the same thing as methods provided by the BylinesAssociation concern, but is far less complex and seems to get the job done.

https://github.com/SCPR/SCPRv4/commit/3b0e4f0a3b52790be276001c20e8eb0d0830a918#diff-3c9e83b5e2e8e4e07661530d76db945cR127

**Comment by nakedsushi** [comment]
Re-opening for the remaining issues Brian reported:

> Also, we don’t normally do three bylines, but where we do, it would ideally be comma-separated, so `Scott Neuman, Camila Domonoske and Colin Dwyer | NPR`
> Also, still unclear when you can click a byline and when you can’t. Used to be blue for staff with linked bio pages, black for everyone else
