### ISSUE TITLE
Add Browserstack Status badge to repo

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#1029]
https://www.browserstack.com/automate/status-badges

AC:
- [ ] viewing the scprv4 repo shows the browserstack status badge

**Comment by Ravenstine** [comment]
This would make sense to add if we were running our view tests inside their environment, but we're not doing that.  The CircleCI badge currently does what the Browserstack badge would do if we just stuck it in here with no actual test integration.
