### ISSUE TITLE
Remove captions falling-back to title

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1051]
AC

- [x] If a caption is left blank, then display no caption

Note: This is based on the understand that currently if the caption is left blank, we fall back to the image title. Given that image titles are not well policed, it's better to display nothing instead of the title.

**Comment by arellaTV** [comment]
Changes are up on production. Waiting for confirmation (will update here)

**Comment by arellaTV** [comment]
Looks like we're good!

## How to mute the caption:
- Go to the asset in asset host
- Make the caption blank (optional: save it to assethost if needed, though probably not in this case)
- The image should now not show a caption
