### ISSUE TITLE
Investigate why Adtech doesn't always respond with ads XML

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#1214]
Website live stream (https://www.scpr.org/listen_live/) sometimes does not have ads. I see an ajax error when this happens, trying to reach https://adserver.adtechus.com/?adrawdata/3.0/5511.1/3590535/0/0/header=yes;adct=text/xml;cors=yes I think.

AC:
- [x] we know why adtechus.com isn't responding properly

**Comment by nakedsushi** [comment]
I can't replicate this anymore.  Tried reloading several times incognito. All the requests to adtech are 200OK. Maybe by procrastinating this ticket, they finally fixed their HTTPS and this issue is now moot? Gonna keep it around in the sprint and see if it comes up again.

**Comment by nakedsushi** [comment]
I'm pretty sure this is an adtechus.com issue and not us.  For example, when the livestream requests an ad, adtechus.com wants to load an xml like so: https://adserver.adtechus.com/?adrawdata/3.0/5511.1/3590535/0/0/header=yes;adct=text/xml;cors=yes but if you click on that right now, you can see that it's not well formed XML and you actually get this error:
```
This page contains the following errors:
error on line 1 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
```
Do we have a contact at adtechus.com that we can send this to?

**Comment by nakedsushi** [comment]
In email w/ adtech support about this.

**Comment by vsinghkpcc** [comment]
The "solution" here then is to have a series of house ads to fill unsold impressions. We stopped doing this given connection issues on third party applications, to prevent constant preroll delivery from re-connection attempts. We should continue this approach until we have a different solution (to either problem).

So, no changes needed at the moment - closing this ticket.
