### ISSUE TITLE
Ensure CA Dream page outputs more than 40 stories

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1237]
AC
- [x] The CA Dream Project landing page exposes all entries with the associated tag: https://www.scpr.org/california-dream-project

Note: the logic currently pulls from our API, which returns a max of 40 articles. The grant requirement is to list all the articles in one place, and to include the CA Dream logo and description, as well the partner logos.

They will likely publish their 41st article towards the end of August / early September. We need to make sure we are in compliance with the grant requirements by the end of Sprint 84.

I see two options - 1) modify the logic on the existing page to be able to include 41+ articles, or, 2) modify the tag page to include the CA Dream Logo and description, as well as the partner logos and redirect this current URL to the tag page.

**Comment by arellaTV** [comment]
A lazy loading list solution is explored on staging here: https://scprv4-staging.scprdev.org/california-dream-project

**Comment by arellaTV** [comment]
New solution is up on production: https://scpr.org/california-dream-project
