### ISSUE TITLE
Elemental Grant: Create display for all stories in partner's RSS feed

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1242]
AC

- [x] There is a flat page that outputs all the stories from this feed, displayed as close to existing scpr.org styles: https://elementalreports.com/partner-feed/

Note: it's possible for us to request changes to the feed, but the change will have to work across all partners involved in this project.

**Comment by arellaTV** [comment]
First pass lives on staging: https://scprv4-staging.scprdev.org/elemental

**Comment by arellaTV** [comment]
Production version: https://www.scpr.org/elemental-reports (thanks Vijay!)
