### ISSUE TITLE
LAist: Provide some form of helper text and/or form validation for link insertion

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1247]
AC:

- [x] There is helper text explaining that a valid url is needed (must include the protocol)
- ~~[ ] The input field is `type="url"` which should add the necessary form validation~~

**Comment by arellaTV** [comment]
It looks like it's a bit more complicated to add the `type="url"` validation than I thought because TinyMCE doesn't use the standard html5 url input in their link widget. After diving into what it would take to add that sort of validation in a custom way, it seems like the better option is to just include helper text. Example below:

<img width="602" alt="screen shot 2018-08-23 at 12 39 30 pm" src="https://user-images.githubusercontent.com/16679701/44548047-d2371100-a6d1-11e8-9aa7-a2459c6a4b20.png">

I think this is better because it still leaves an opportunity for links to be sourced locally, i.e. urls that target specific elements by id with the `#` symbol.

It should be ready to be pushed to production later tonight with the autocomplete feature

**Comment by nakedsushi** [comment]
This is a good compromise 👍
