### ISSUE TITLE
SCPRv4: Update CircleCI to 2.0 and Investigate CI Timeout Issues

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1251]
Circle CI 1.0 is being sunset on August 31st, so they request that we update to 2.0 before then. Also, there have been some issues with tests timing out, and asynchronous tests failing occasionally.

AC:

- [x] Update Circle CI to 2.0
- [x] Do an audit for common fault points in the ci process
- [x] Eliminate any tests that aren't needed anymore and are asynchronous
- [x] Investigate timeout issues

**Comment by nakedsushi** [comment]
This was a dupe of https://github.com/SCPR/digital_products/issues/510 but since this ticket is actually useful and has AC, gonna close https://github.com/SCPR/digital_products/issues/510 for this one.

**Comment by arellaTV** [comment]
Circle CI 2.0 has been updated successfully, but it still intermittently fails. I think I should periodically prune tests that are inconsistent when I experience them.
