### ISSUE TITLE
Show landing page logos: Update with registered marks

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1252]
AC: Update all relevant show pages with a logo that includes the registered mark

- [x] The Frame
- [x] Take Two
- [x] AirTalk

**Comment by jo-im** [comment]
I have updated all the landing logos with registered marks and merged my changes to master.
Here are screenshots of all the landing logos with registered marks:

The Frame:
![Screen Shot 2018-12-07 at 2.15.46 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/86d1700b-2041-4597-a1dd-be61912a0382)

Take Two:
![Screen Shot 2018-12-07 at 2.15.26 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/8c7dadd8-030e-4b76-808f-dd08f1381111)

AirTalk:
![Screen Shot 2018-12-07 at 2.15.07 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/b665e3ae-87b6-4c08-acd3-a240fef2fcb1)

Here is the commit that made these changes:
https://github.com/SCPR/SCPRv4/commit/8a39f4c46e43f743aacd551b80da563955267473
