### ISSUE TITLE
LAist: Fix RSS Feed Validation Errors

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1259]
It looks like the RSS feed integration for #kpcc-laist-stories is inconsistent when it comes to retrieving newly published articles. The biggest clue is this:
http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Flaist.com%2Findex.rdf

There's some work to be done to ensure that it works in the widest range possible for rss readers.

AC:
- [x] The above validation errors are resolved

**Comment by jo-im** [comment]
I have resolved all validation errors in the link above, so the RSS feed integration for #kpcc-laist-stories should be consistent when it comes to retrieving newly published articles. I have pushed and merged my fix to master.

Here is the feed validator response for https://laist.com/index.xml.
![Screen Shot 2018-12-05 at 5.12.07 PM.png](https://images.zenhubusercontent.com/58d7395251aa2c3057797c0d/c3d02393-c945-419b-b514-fdca2bc4af75)

You can find my commit for this fix here:
https://github.com/SCPR/movabletype-laist/commit/9466cf5d7e4d974d12fa3d1a503d725466920672
