### ISSUE TITLE
LAist: Change default image to LAist branded one

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1294]
![Screen Shot 2018-09-11 at 11.00.28 AM.png](https://images.zenhubusercontent.com/58c1ab5051aa2c30577801b7/d6bd80ef-d3c2-42d3-8feb-6e6ffaf8f241)

AC:
- [ ] The default fallback photo is changed to an LAist branded one

**Comment by nakedsushi** [comment]
I have some time to kill, so I can take this one off @jo-im's plate today.

**Comment by nakedsushi** [comment]
Issue moved to [SCPR/digital_products #790](https://github.com/SCPR/digital_products/issues/790) via [**ZenHub**](https://www.zenhub.com/)
