### ISSUE TITLE
LAist MT: Fix missing ordered list

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1299]
Mike Roe pointed out that ordered lists don't work in LAist MT.

AC:
- [x] Ordered lists in the body render as ordered lists in the final copy

**Comment by nakedsushi** [comment]
Let's give this one to @jo-im with @arellaTV pairing (as the navigator) on this. This could be Jo's first LAist task. Gonna bump the estimate to a 2 to get her all set up w/ deploying LAist.

**Comment by jo-im** [comment]
Was able to push the fix to production with this commit: https://github.com/SCPR/movabletype-laist/commit/cdc006c00db382c853d29be901bbd34a74fb8095
