### ISSUE TITLE
Megaphone: Investigate issues with auto-upload from outpost

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1306]
There's an issue where audio files being served from Megaphone is longer than the original length. This sounds like it's due to some timing issue.

AC:
- [x] Figure out if it's an asynchronous issue
- [x] Try to manually recreate the bug
- [x] Check if we're using the right completion hook

**Comment by arellaTV** [comment]
I was able to recreate the bug on staging (input file was an Airtalk episode that ran ~90min., the resulting file goes for ~148min.)

Async issues seem probable as the frame is still largely unaffected by the bug (since the URL is only ready after the file has completed processing)

**Comment by arellaTV** [comment]
I've tested it extensively on staging with a new completion callback:
```
after :cache
```
and that appears to be working consistently. I think it's worth giving that callback a try and monitoring closely for a sprint or two.

**Comment by arellaTV** [comment]
Since the previous attempt failed, I think it's better to update the AC for this ticket.

AC:
- [ ] There is a job that runs every 20 minutes
- [ ] The job collects the latest episode from each podcast that has a valid megaphone url
- [ ] The job checks if the latest episodes have the same file size as the files on megaphone
- [ ] If there's a size discrepancy, it attempts to re-upload the file

**Comment by arellaTV** [comment]
Discovered today that the application was making PUT requests with url's without waiting for the file to be stored on our server drive space. I changed up the conditions so that it only performs a put request with a change in url if that url isn't from our media server. I tested about 2 weeks worth of content with no apparent errors. I think this might be the likeliest explanation and one worth exploring in production for a couple of weeks.

**Comment by nakedsushi** [comment]
Wow, good find!

**Comment by arellaTV** [comment]
Created a new ticket for the effort involved with a health-check job: https://github.com/SCPR/SCPRv4/issues/1334

**Comment by nakedsushi** [comment]
Wait, this is not done. Code is still being worked on.
