### ISSUE TITLE
The Big One: Data Visualization

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1311]
AC:

- [ ] There is a styled search bar
- [ ] There is a styled filter box
- [x] There is a styled breakdown box
- [ ] The breakdown box knows when a pin is above specific layers and reports accordingly
- [x] Able to run the map locally

**Comment by jo-im** [comment]
Cut this ticket to two separate smaller tickets which can be found here:
https://app.zenhub.com/workspaces/55a576e252c92c86166be11b/issues/scpr/scprv4/1357
https://app.zenhub.com/workspaces/55a576e252c92c86166be11b/issues/scpr/scprv4/1358

**Comment by jo-im** [comment]
My progress so far is that I'm able to run the map locally. A user can also search for an address and there will be a pin that drops on that address. Also, I created the styled breakdown box which shows the correct searched address.

Here's the screenshot of what I have so far:
<img width="1343" alt="screen shot 2018-11-14 at 3 37 04 pm" src="https://user-images.githubusercontent.com/16568530/48519959-b13f1180-e823-11e8-981a-044aa1b058ba.png">
