### ISSUE TITLE
SCPRv4: Banner ads clipping

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#1325]
**Let's get this change in by Nov 9th so that we don't need to deploy to SCPR during pledge week.**

Andy shared this image:

![image.png](https://images.zenhubusercontent.com/58c1ab5051aa2c30577801b7/5e390cd0-d870-488f-81b0-f820c712929b)

I think it's because the ad resize function isn't being invoked correctly.

AC:
- [x] The ad resize feature is being invoked correctly
- [x] The ads resize and uncropped on medium sized screens

**Comment by nakedsushi** [comment]
Let's get this change in by Nov 9th so that we don't need to deploy to SCPR during pledge week.

**Comment by jo-im** [comment]
I have successfully merged my fix to master so ads are resizing properly and uncropped in medium and small screen sizes. I have also tested the ad resizing in Chrome, Safari, Firefox, Internet Explorer, and Microsoft Edge. 

The commit that holds this fix is here:
https://github.com/SCPR/SCPRv4/commit/0de2c9041877ce28604c38adbfe984a74f18603d
