### ISSUE TITLE
LAist Member Testimonials: Research On How To Alter MovableType API response

### ISSUE THREAD

**Issue by jo-im** [SCPR/SCPRv4#1367]
I figured out how to associate two content types together and I was able to create two content types: Membership Testimonials and Lists.

Member testimonials have fields for multi-line texts and image assets and Lists can hold multiple Member Testimonials. MovableType is able to associate two content types out of the box, however, when performing a GET request to that endpoint, it returns ids and not records. So I need to research more if there's a way to serve the records instead of the ids when two content types are associated.

AC: 
- [ ] Find where the API response is being generated
- [ ] Figure out why ids are being returned
- [ ] See if there is a way to receive records rather than ids
- [ ] If it is too complicated, fallback to working with the ids

**Comment by nakedsushi** [comment]
Issue moved to [SCPR/digital_products #846](https://github.com/SCPR/digital_products/issues/846) via [**ZenHub**](https://www.zenhub.com/)
