### ISSUE TITLE
LAist Member Testimonials: Individual Testimonials Are Rotated In a Round-Robin Fashion

### ISSUE THREAD

**Issue by jo-im** [SCPR/SCPRv4#1368]
AC:
- [ ] Able to parse data from Member Testimonials Content Data
- [ ] There's a round-robin with a member testimonial on top of every entry when Member Testimonials is published
- [ ] Testimonials are rotated on every load/reload of the page
~- [ ] The round-robin rotates every three seconds~
~- [ ] There are buttons on the round-robin that can be clicked to rotate each testimonial~

**Comment by nakedsushi** [comment]
@jo-im Just clarifying, but the testimonials should rotate on each load/reload of the page, right? Not live-reload every 3 seconds when someone is on the page?

**Comment by jo-im** [comment]
@nakedsushi Hi Louise! Sorry, I think I must have misunderstood. I thought the testimonials was supposed to be a carousel but I'll update the ticket right now so the AC will be testimonials rotating on each load/reload of the page. Thank you so much for catching that!

**Comment by nakedsushi** [comment]
Issue moved to [SCPR/digital_products #847](https://github.com/SCPR/digital_products/issues/847) via [**ZenHub**](https://www.zenhub.com/)
