### ISSUE TITLE
LAist Member Testimonials: Tracking On Which Testimonials Generate The Most Lead

### ISSUE THREAD

**Issue by jo-im** [SCPR/SCPRv4#1369]
AC: 
- [ ] Push to data layer every time a testimonial is clicked
- [ ] Can view how many clicks each testimonial has

**Comment by nakedsushi** [comment]
Issue moved to [SCPR/digital_products #848](https://github.com/SCPR/digital_products/issues/848) via [**ZenHub**](https://www.zenhub.com/)
