### ISSUE TITLE
LAist Member Testimonials: Turn Testimonials Off When Member Testimonials Are Unpublished

### ISSUE THREAD

**Issue by jo-im** [SCPR/SCPRv4#1370]
AC: 
- [ ] Remove testimonials from the top of all entries when Lists Content Data (which contains multiple Member Testimonials Content Data) is unpublished

**Comment by nakedsushi** [comment]
Issue moved to [SCPR/digital_products #849](https://github.com/SCPR/digital_products/issues/849) via [**ZenHub**](https://www.zenhub.com/)
