### ISSUE TITLE
LAist Member Testimonials: Testimonial Content Can Be Saved And Edited By Membership

### ISSUE THREAD

**Issue by jo-im** [SCPR/SCPRv4#1371]
AC:
- [ ] There's a Member Testimonials Content Type
- [ ] Can add multi-line texts for each Member Testimonials Content Data
- [ ] Can upload an image for each Member Testimonials Content Data
- [ ] There's a Lists Content Type
- [ ] Lists Content Data can hold multiple Members Testimonials Content Data

**Comment by nakedsushi** [comment]
Issue moved to [SCPR/digital_products #850](https://github.com/SCPR/digital_products/issues/850) via [**ZenHub**](https://www.zenhub.com/)
