### ISSUE TITLE
Latest News - filter out NPR content

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1375]
AC
- [x] Update the channel <channel> / <title> to be "Latest News from KPCC" 
- [x] Add <channel> / image> elements and sub-elements as detailed here: https://developers.google.com/news/assistant/reference/specifications#image
- [x] The Latest News "podcast" feed does not include NPR content

**Comment by arellaTV** [comment]
The above updates should now be in place: https://www.scpr.org/podcasts/news
