### ISSUE TITLE
Create print email sign-up form

### ISSUE THREAD

**Issue by jgeorges** [SCPR/SCPRv4#1387]
Based on Marketing meeting discussion.

**Comment by jgeorges** [comment]
Created 4-up form. Shared .ai file with Stephanie. Handing off.

[Newsletter_Form.pdf](https://github.com/SCPR/SCPRv4/files/2742561/Newsletter_Form.pdf)

**Comment by vsinghkpcc** [comment]
Handed off to Steph, closing.
