### ISSUE TITLE
LAist About in production

### ISSUE THREAD

**Issue by jgeorges** [SCPR/SCPRv4#1420]
- [x] Get access to LAist production admin
- [x] Copy staging about into production
- [x] Coordinate with Jay on adding to menu

**Comment by nakedsushi** [comment]
@jgeorges I created an account for you in LAist production. Username is the same as you have on staging, but you'll need to reset the password on production to log in.

**Comment by jgeorges** [comment]
What is the URL for production LAist admin?

**Comment by jgeorges** [comment]
Added the about page to LAist.com, currently in Draft. 
https://laist.com/mt-preview-9a59617e73230d2608e6bf0631414e09394e48de.php

Will eventually live at: https://laist.com/about-us.php

Link to edit: https://laist.com/mt/admin?__mode=view&_type=page&id=85128&blog_id=1&saved_added=1

**Comment by jgeorges** [comment]
https://laist.com/about-us.php is published.

**Comment by jgeorges** [comment]
https://laist.com/ about menu is updated. 
Worked with Jay, forked the LAist github repository. updated movabletype-laist/themes/laist/templates/banner_header.mtml, merged. Pushed. Yay!
