### ISSUE TITLE
Content Items With Multiple Assets Should do Batch Lookup

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#227]
Slow page loads often produce a transaction trace that looks similar to this one:

![screen shot 2014-10-27 at 1 36 50 pm](https://cloud.githubusercontent.com/assets/204350/4795904/09fbc4ce-5e00-11e4-9c1d-9bcedf3468f3.png)

We're fetching asset details one-at-a-time instead of hitting an endpoint that can return all of the story's assets at once. This doesn't really affect new stories, where the CMS ends up warming the asset cache, but it makes loads much slower after items fall out of the cache. 

Story for this trace was: http://www.scpr.org/news/2014/01/16/41634/la-county-firefighters-battling-wildfire-in-angele

**Comment by Ravenstine** [comment]
Yeah, not really sure about this one.  Page load time seems fine to me as well.
