### ISSUE TITLE
Program pages should include their own RSS in their meta headers

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#246]
Was just chatting about this with Collin. He wants to make sure that people can easily figure out RSS links from just the normal show pages. I mentioned that there should already be metadata in the headers to link readers to that, but then I looked and there currently isn't (though The Frame's includes a link to the all_news RSS).

@sdillingham: Let's chat and make sure we're on the same page on this, and maybe we can sneak this into the template changes rolling out this week.

**Comment by sdillingham** [comment]
Sounds good. I'm sure we can add this in as part of this week's deploy.

**Comment by ewr** [comment]
I think for the new templates, it should just be a matter of populating meta_information, so that it gets picked up here: 

https://github.com/SCPR/SCPRv4/blob/5a95ca97521c9e4b831348ed8ab09d9410b2f106/app/views/shared/new/_document_header.html.erb#L35

Should we be filling out all of those fields for shows? I don't think anything is calling that helper right now.

**Comment by ewr** [comment]
Thursday's deploy of #247 resolves this for The Frame, Take Two and Off-Ramp. Should we also fix Airtalk before closing this issue?

**Comment by ewr** [comment]
@sdillingham Thoughts on closing vs resolving Airtalk?

**Comment by sdillingham** [comment]
This should be fixed with https://github.com/SCPR/SCPRv4/commit/7ae8fa1.
