### ISSUE TITLE
Feature audio id needs to strip / throw error on invalid characters

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#248]
Just saw this issue in New Relic:

`URI::InvalidURIError: bad URI(is not URI?): http://media.scpr.org/audio/features/20150326_features1076 .mp3`

The issue is the space between `1076` and `.mp3`.

We need a validation on `Audio.enco_number` to make sure whitespace (or any other non number characters) can't get inserted.

**Comment by Ravenstine** [comment]
I actually worked on this a while ago but didn't make a pull request for it.  Had to change it slightly, though.  

https://github.com/SCPR/SCPRv4/pull/321
