### ISSUE TITLE
Podcast feeds should support a "consumer" param

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#250]
Currently our podcast feeds expose two parameters (`context` and `via`) when constructing audio enclosure URLs that are used for tracking purposes. See:

https://github.com/SCPR/SCPRv4/blob/master/app/views/podcasts/podcast.xml.builder#L51-L54

`via` is used to ascertain what channel the audio was published from (e.g., "podcast," "website," "api"); `context` is used to reliably pass in the entity/show the audio belongs to (e.g., "airtalk," "the-frame," "latest-news").

We need a third parameter to track specific 3rd-party consumers of our feeds so we can know with confidence which aggregators are driving the greatest amount of podcast downloads. The goal would be to allow `?consumer=xxx` to be appended to any podcast URL (e.g `http://scpr.org/podcasts/the-frame?consumer=iheartradio`), and have the podcast feed generator key off that param and inject it into all audio enclosure URLs for the given feed.

**Comment by ewr** [comment]
Closed via #257

**Comment by ewr** [comment]
So... we missed the caching...

**Comment by ewr** [comment]
Fixed via #259.
