### ISSUE TITLE
Issues should pull coverage dates from articles

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#251]
Right now, issue coverage dates are based on `created_at` and `updated_at`, which works ok for the case where an issue is created before any articles are published.

However, if the issue is created later to aggregate existing articles, the display is incorrect:

![screen shot 2015-05-01 at 10 48 10 am](https://cloud.githubusercontent.com/assets/204350/7431761/c93055f4-efef-11e4-8c82-c50ed523dc18.png)

Two possible solutions:

1) Query the date range from the articles at display time.
2) Create `began_at` and `most_recent_at` attributes on the Issue object, and then do something in the tagging save process to update them.

The latter is more efficient. `created_at` and `updated_at` for this are hacks that have always been wrong, it was just never really visible enough to bother anyone.

**Comment by Ravenstine** [comment]
I've added the new timestamp columns and changed the TagsAssociation#touch_tags method to also update the most_recent_at timestamp.

Maybe what we also want is to have the began_at timestamp sync up with the earliest associated article on before_save?

**Comment by ewr** [comment]
Yeah, we would want to update the `began_at` if our content's `published_at` is before the existing value.

**Comment by ewr** [comment]
Closed by #260.
