### ISSUE TITLE
Add captioning for in-line photos in KPCC stories

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#270]
At the moment, we manually add captions beneath in-line photos on KPCC stories. It's a fine work-around, but could create problems down the road. Ideally, we'd be able to add style elements to inline photo captions so that they're consistent and clearly associated with the image, rather than undifferentiated blocks of text within a post (ex. http://kp.cc/1wTIqlg).

**Comment by sdillingham** [comment]
This issue has moved to #313 - we'll track its progress over there. Closing this issue.
