### ISSUE TITLE
/api/schedule/ endpoint should support a concept of representing whether there's currently an on-air pledge drive

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#280]
In order to extend the pledge-free stream beyond SCPR.org and into our apps, API clients will need a way to know whether KPCC's is in the middle of an on-air pledge drive. Long term this could map to larger concepts around modelling stations, but to start this could be something simple like a `pledge_drive_is_active` boolean that is set manually and passed through in the API response.

**Comment by ewr** [comment]
:+1: I'd just go with a `pedge_drive` boolean for now, sitting next to the `schedule_occurrences` array in the returned object.

**Comment by Ravenstine** [comment]
Do we care about the v2 API?  If we don't, I'm thinking we could just stick the boolean in the JSON builder for the v3 API.  If we do, maybe it would be better to have an initializer create a constant that stores the pledge_drive boolean.

**Comment by ewr** [comment]
Currently we're only talking about the iPhone app, which only consumes the v3 API.

**Comment by Ravenstine** [comment]
Is now added and I'm confident it's working as it should.
