### ISSUE TITLE
Some characters cause the preview for a news story to fail in Outpost.

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#286]
For example:
http://www.scpr.org/outpost/news_stories/52185/edit

The apostrophe character(likely other UTF-8 characters too), when used in a headline or an asset caption, cause this error when the caption is rendered in a preview(from app/views/shared/assets/news/_photo.html.erb:13):

```Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8```

Here's the offending string from the headline: 

"California is sinking, and it’s getting worse"

... and the string from the asset caption:

"Michelle Sneed, a hydrologist with the geological survey, duplicated a photo by legendary hydrologist Joseph Poland to show a land sinking problem. Her photo, shown here, captures the early stages of today’s worsening subsidence problem."

The error occurs when the character is present in BOTH the headline and the asset caption.  It's possible that this applies to other text fields as well.  When the apostrophe in "today’s" is removed(or replaced with a tick), the error is not encountered and the preview renders.  The error also goes away if the apostrophe is removed from the headline.

This problem only seems to happen in production when previewing in Outpost.

https://rpm.newrelic.com/accounts/71496/applications/446356/traced_errors/63981c-c2238924-0ad8-11e5-88d6-c81f66b8ceca

**Comment by ewr** [comment]
@Ravenstine: If you've verified this in production, go ahead and close it.
