### ISSUE TITLE
Embed.ly embed API requests returning 403 errors

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#289]
We dynamically replace links to specific 3rd party content on our articles using a combination of embed.ly (a SaaS embeds product) and a library we wrote ourselves (https://github.com/SCPR/embeditor-rails) that provides adapters for common embeds. We've begun experiencing an issue where all embeds that are delivered via embed.ly are failing to load. A couple of sample URLs for reference (use web inspector in your browser to see the API call failures):

A Vimeo embed: http://www.scpr.org/blogs/multiamerican/2014/10/31/17493/hello-kitty-con-superfans-los-angeles/

YouTube embeds: http://www.scpr.org/blogs/newmedia/2015/02/26/17957/unauthorized-power-rangers-movie-starring-james-va/

These were pages where embeds were loading correctly at one time, but now we're seeing 403 errors for all our embeds across the site. This could be an API key issue, or something that changed with their API. 

To see usage and API key information associated with our account, you'll want to log in to embed.ly's admin dashboard.

**Comment by Ravenstine** [comment]
This is actually an issue with Embeditor.  I'll make a PR tomorrow morning.

**Comment by ewr** [comment]
@Ravenstine: If you've verified the fix in production, go ahead and close this.
