### ISSUE TITLE
Install Nielsen SDK on Web

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#311]
AC
- [x] Install Nielsen SDK
- [x] Validate the proper data is being sent to Nielsen

**Comment by Ravenstine** [comment]
Unless I'm mistaken, it appears that I need to create an account in the Nielsen developers area and wait for it to be approved before I can even get more details on the SDK.  I have done so now and we'll see what happens.

**Comment by Ravenstine** [comment]
From what I have read from their documentation, they want us to send metadata on every play.  This metadata just contains things like our station name and type.  Right now, it just sends the same thing every time; do we want different metadata when non-KPCC shows are on?

Example of metadata being sent through the SDK:
```coffee
                @nielsen.ggPM "loadMetadata",
                    stationType: 2
                    dataSrc    : "cms"
                    type       : "radio"
                    assetid    : "KPCC-FM"
                    provider   : "American Public Media - Radio"
```

**Comment by ewr** [comment]
No. It's station/stream metadata, not content metadata.

**Comment by Ravenstine** [comment]
Ok, I wanted to make sure it wouldn't mean changing our provider string.

**Comment by vsinghkpcc** [comment]
From Nielsen:
We have completed certification of your test player and observed no issues – the SDK behaved as expected, we saw all of the proper pings for Digital Audio measurement fire accordingly, and duration credited properly.
 
To conclude certification of your test player, we’ll need to do a final sanity check of it with your Production values in place.  It’s very rare that any issues would arise with your Production values in place but it is a precaution we prefer to take within your test player first before you actually deploy the integration to your production player.

[production values sent to @Ravenstine via slack]

Please let me know once this has been done, so we can conduct a final sanity check of your test player.
 
KPCC Radio is also still in the process of signing our Production License Agreement (which covers having our SDK on their station player go live to the public) so please do not deploy into production until further notice.

**Comment by Ravenstine** [comment]
NOTE: The production values have already been added to staging and we are waiting to hear back from Nielsen.

**Comment by Ravenstine** [comment]
Installed and in production.

**Comment by vsinghkpcc** [comment]
@Ravenstine Heads up - Nielsen reached out and asked us to updated the production value (which I'll send via Slack).
