### ISSUE TITLE
Outpost user can easily add inline assets to stories

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#313]
AC 

1) Outpost users can easily add inline images from AssetHost
2) Outpost user can customize the caption for this instance of the asset, or use the canonical caption by default
3) The asset chosen by an outpost user (including caption and credit) is displayed on the front end 
4) There is a fallback for when asset delivery can't be handled on the front end

**Comment by sdillingham** [comment]
Depends on #314.

**Comment by sdillingham** [comment]
I think this is a meta-issue currently being addressed by #333, #337, and #340, which are either done or close to meeting AC. Closing.
