### ISSUE TITLE
Research: Inventory Current API Consumption

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#320]
AC
1) Establish a way to inventory all things consuming all versions of the API
2) Create document with inventory of all things consuming all versions of the API

**Comment by sdillingham** [comment]
Here's an example of a flatpage in SCPRv4 that's using the v3 API to build a collection of articles:

http://www.scpr.org/first-person-series

**Comment by Ravenstine** [comment]
Of what goal is this a step towards accomplishing?

**Comment by sdillingham** [comment]
This was a first step on the path to a v.Next API for our products. The idea was to understand all the places where the v2 and v3 APIs are being used, so that we can know what the scope of work would be to migrate all our API clients to a new API and not have to keep old endpoints around forever.

**Comment by Ravenstine** [comment]
Thanks @sdillingham

**Comment by Ravenstine** [comment]
I don't agree that we need a v4 API endpoint.  We might want to sunset the v2 API, but the path for that is pretty clear as that's only used within Outpost.  Neither of our mobile apps use it, and even if the iPad does, it'll be sunsetted long before we ever get to deprecating the v2 API.
