### ISSUE TITLE
New editions published on Monday should create a second email campaign via Eloqua API 

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#322]
Currently, SCPRv4's Edition model implements the `eloqua_sendable` concern to fire off a new email campaign for each edition that is published:

https://github.com/SCPR/SCPRv4/blob/master/app/models/edition.rb#L118-L143

This results in a single campaign + email being created via the Eloqua API. Check out the eloqua_sendable concern to understand a bit more about how we're integrating with the Eloqua API: 

https://github.com/SCPR/SCPRv4/blob/00555900e1fda9930c7c6b38d0e15ca2e20f8048/app/concerns/concern/methods/eloqua_sendable.rb

In order to extend the reach of The Short List, we want to send the Edition that gets published every Monday to a separate, larger email segment in Eloqua. We will need to augment the Edition model to support the creation of a second campaign + email that is associated with a different segment.

The AC for this feature are:

* On Tuesday-Sunday, any new published Editions will continue to generate a single campaign + email in Eloqua. (this is how SCPRv4 currently functions, and it should remain unchanged.)
* Any Edition published on a Monday should generate two Eloqua emails + campaigns: the one we currently generate, plus a new one that sends to a different segment
* The new email we send should use a different HTML template from the one we currently use for the M-F Short List. Here's the code to use: https://gist.github.com/sdillingham/5e5cf4a723c69af9acb9 
* The new email should use the same `email_group_id`, `campaign_folder_id`, and `email_folder_id` that is in our secrets.yml file under `api -> eloqua -> attributes -> edition`. The value for `segment_id` should be `4250`. You'll want to work with @vsinghkpcc to find a test segment to work with during development so you're not testing this feature out by sending emails to 60k people. :smile:

**Comment by sdillingham** [comment]
One more thing: each email template has an HTML and a plain text version, so you'll need a new template for each of these versions. I've updated the gist to include the plain text template as well as the HTML template:

https://gist.github.com/sdillingham/5e5cf4a723c69af9acb9

**Comment by ewr** [comment]
This was deployed yesterday without production config getting updated, causing the shortlist to fail to send this morning. 

I believe I've now deployed the correct config, but that should get a second look from someone who knows more Eloqua.

**Comment by ewr** [comment]
From Bryan Frank:

> just fyi, when Lisa published the SL this morning, it went to Eloqua, but now it’s not getting the checkoff in the CMS. Like it’s not registering that it was delivered...

**Comment by Ravenstine** [comment]
@ewr I'll work on patching that.  I think I know what's happening and it should be a simple fix.

**Comment by sdillingham** [comment]
Verified that the Monday send is being created properly in Eloqua and is also being checked off in Outpost. Closing.
