### ISSUE TITLE
Unchanged RecurringScheduleRules are getting saved nightly

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#325]
I suspect this came out of #310... 

<img width="1172" alt="screen shot 2015-08-17 at 1 39 42 pm" src="https://cloud.githubusercontent.com/assets/204350/9311635/71942c44-44e5-11e5-8a20-9c0445bd7872.png">

I'm guessing the ScheduleOccurrence is causing the recurring schedule rule to save (or touch?), and that the outpost history code doesn't have a way to understand state on a serialized attribute (which is always dirty, from Rails' perspective).

**Comment by sdillingham** [comment]
Verified that Recurring Schedule Rules are no longer being touched/saved daily. Closing.
