### ISSUE TITLE
Validate if Google Content Experiments is a workable solution for our tests

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#329]
AC

1) Validate if Google Content experiments can run the A/B tests we want for our Newsletter CTA at the bottom of story pages

**Comment by Ravenstine** [comment]
Not sure if relevant but seems related:
http://stackoverflow.com/questions/18525155/google-analytics-content-experiments-regex-in-url

**Comment by Ravenstine** [comment]
I'm really not finding any alternatives that do what we want that also don't have the same problems(such as pricing) as Optimizely.  @sdillingham and I have concluded that Google Content Experiments won't suffice, at least without jumping through multiple hoops.  At the same time, any open source A/B testing implementations would require as much or more work as if we used Google.  I'm going to put this ticket in the 'done' bucket, though if I come across anything new before the end of the sprint, I'll add it here.

**Comment by sdillingham** [comment]
I consider the research complete on this issue. Closing.
