### ISSUE TITLE
Inline Assets: AssetHost and WYSIWYG communication

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#333]
AC

1) The image button in the toolbar triggers UI state change (ex. asset collection in right sidebar)

2) A user can drag and drop images from the asset collection into the body WYSIWYG

3) There is a solution for syncing state between Asset Collection and WYSIWYG

4) A user can dismiss the asset collection UI (ex. having an "exit" button that dismisses the panel)

**Comment by vsinghkpcc** [comment]
Remaining AC

1) Use of an inline asset is visually represented in the asset collection
2) Images currently used inline cannot be dragged / dropped into the editor again 
3) An image dropped into the editor does not live in the middle of a p tag
4) The image button in the toolbar triggers UI state change to allow drag / drop of assets
5) A user can dismiss the asset collection UI

**Comment by vsinghkpcc** [comment]
Remaining AC

1) Tests
2) adjustments based on feedback

**Comment by Ravenstine** [comment]
I'm putting this into review, though staging is having problems that are not related to the code.

**Comment by Ravenstine** [comment]
PR merged.
https://github.com/SCPR/SCPRv4/pull/347
