### ISSUE TITLE
AirTalk Program Landing Page

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#336]
AC

1) There is a landing page for AirTalk using the "new" template
2) All segments for the latest episode are displayed in the episode summary
~~3) Comments for each segment are conditionally displayed (i.e. if AirTalk, display comments)~~
4) Custom image assets for AirTalk have been created for the page

**Comment by Ravenstine** [comment]
Just as a note: My part of this is done unless something else comes up.

**Comment by Ravenstine** [comment]
Note #2: I've made the few little changes we discussed during demo.

**Comment by sdillingham** [comment]
Assets for AirTalk's landing page have been added with this commit:

8520387342cd85d32112f4a866aa9f1e3d835eec

Reassigning to @Ravenstine and will add a comment with some thoughts about a quick refactor of the logic in our program landing page code.

**Comment by sdillingham** [comment]
@Ravenstine: now that our VWO test confirmed that we can do without comment counts on the segment rundown for the latest AirTalk episode, I think it's possible to refactor our logic in the `_featured_story` partial to remove any hardcoded references to AirTalk:

https://github.com/SCPR/SCPRv4/blob/airtalk_page/app/views/programs/kpcc/_featured_story.html.erb#L45-L67

What if, instead, we display all segments for any episode where `story_segments` contains 8 or fewer segments? Then we're not tying the logic to a specific show, but rather a specific condition (an episode has fewer than 8 segments). 99% of the time that will apply to shows like AirTalk or The Frame, so the result will be the same.

If we go down this road, I believe we should remove this reference to AirTalk as well:

https://github.com/SCPR/SCPRv4/blob/airtalk_page/app/views/programs/kpcc/featured_program.html.erb#L12

**Comment by Ravenstine** [comment]
@sdillingham Yeah, I like that idea.  I think it'll be simpler just to ditch the existing branch and keep the template show-agnostic.

**Comment by Ravenstine** [comment]
@sdillingham Those changes sound good to me.  They are now reflected on the branch so if it looks good to you, I guess it's time to show the AirTalk team and then ship it.

**Comment by sdillingham** [comment]
:+1: Looks good to me. @vsinghkpcc let us know how/when you want to present this to the AirTalk crew.

**Comment by vsinghkpcc** [comment]
Remaining work: get SCPRv4 running locally on Vijay's machine so he can show this to stakeholders.

**Comment by Ravenstine** [comment]
Until something else comes up, I've done as much as I can for now.  Let me know if anything more is needed of me.

**Comment by vsinghkpcc** [comment]
Yep thanks @Ravenstine, I'll work on getting AirTalk sign-off.

**Comment by vsinghkpcc** [comment]
AirTalk approved! We'll be getting the info for the credits section from Lauren Osen.

We also let her know we could push this in the afternoon after the show is off-air, but before staff goes home so they could get familiar with the new layout.

@Ravenstine can you push this tomorrow after 1pm?

**Comment by Ravenstine** [comment]
@vsinghkpcc Yup, I'll be ready to push it.

**Comment by sdillingham** [comment]
This work has been delivered at http://www.scpr.org/programs/airtalk/. Closing.
