### ISSUE TITLE
Inline Assets: Front End Work

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#337]
AC

1) There are agreed upon conditions for when we use block vs. float
2) Logic implemented in scprv4 to render assets based on those conditions
3) Assets look pretty (especially when using float) across our story templates (ex. segments template)

**Comment by Ravenstine** [comment]
@sdillingham @vsinghkpcc 

The display of the inline assets is here:
https://github.com/SCPR/SCPRv4/blob/inline_assets/app/assets/stylesheets/new/single.css.scss#L817

This is an example with a narrow asset and a wide asset:
http://scprv4-staging.scprdev.org/news/2015/06/26/52360/ranker-test/

Let's figure out where to go from here.

**Comment by sdillingham** [comment]
Nice work @Ravenstine, and thanks for the example. I think the ball is now in my court to add design polish to this ticket.

**Comment by sdillingham** [comment]
Styling of inline assets is addressed in 1d6383a00997c37cdb4d0592d74fbb4ce7f0e700.

**Comment by vsinghkpcc** [comment]
Will be providing the digital news team an overview later this week. Let's hold off on shipping until they've gotten a little training. I'll update the ticket once they're ready for us to ship.

**Comment by vsinghkpcc** [comment]
News team trained - let's :shipit:!

**Comment by Ravenstine** [comment]
PR merged.
https://github.com/SCPR/SCPRv4/pull/347
