### ISSUE TITLE
Recurring Schedule Rules Preview

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#339]
AC: There's a way to preview recurring schedule rules, in case there's overlap or gap, in Outpost.

**Comment by Ravenstine** [comment]
Currently, I have a preview window(same mechanism used by other outpost views to preview content) that shows the gaps and overlaps created by the specific Recurring Schedule Rule that you are editing.

Do we only want to show conflicts for that specific RecurringScheduleRule, or should we just show all existing conflicts? (or maybe both concepts separately?)

**Comment by sdillingham** [comment]
After looking over this together, I think it makes the most sense to display one block that shows any conflicts related to the rule you're currently editing, and then a block below that that shows any other conflicts.

**Comment by Ravenstine** [comment]
So here's where I am with this ticket:

For whatever reason, I still seem to be having inexplicable issues when previewing a schedule.  The problem of having gaps/overlaps arise with no actual RecurringScheduleRule changes seems to come and go for me, at least on my local machine.  I've spent way too much time on this, so if anyone has any better ideas, let's definitely hear them.

## Things I've Tried

- Building new schedule occurrences for the current rule, mixing them in with existing schedule occurrences(except those that match the current rule ID), sorting that list, and then finding any gaps or overlaps.  This is how my current implementation works.

- Temporarily deleting the existing schedule occurrences for the current rule, creating new ones, query for all schedule occurrences(sorted by starts_at ASC), and look for gaps/overlaps using the existing #problems class method in ScheduleOccurrence.  This yields for me the same problem, even if I only create new schedule occurrences up to the last `ends_at` for all existing occurrences.  

- Running Job::BuildRecurringSchedule.perform after saving the current rule(with either new attributes or existing).  This really makes no sense, because this should build almost the exact same schedule that currently exists in production(except some more into the future).

- Instead of comparing schedule occurrences, comparing every RecurringScheduleRule by their schedule objects(ala Ice Cube gem), generating arrays of start/end times(basically a simplified version of how ScheduleOccurrences are already being built), combining them into one array, sorting by starts_at, and looking for gaps/overlaps.  Yet again, I'm getting problems where none should exist.

I will note that running Job::BuildRecurringSchedule.perform on its own without even so much as updating the attributes on any rule yields no problems, which would suggest that somehow there's a problem with how data coming from the Outpost edit form is being interpreted by the RecurringScheduleRule model.  But I just can't see how that is so.

I'll leave the pull request up for now, but I'm going to put this aside because I'm tired of putting other work aside and losing sleep over it.
