### ISSUE TITLE
Editions should have bylines

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#341]
Justification: Editions take a significant amount of copywriting and editorial judgment to put together, but currently have no attribution. As long as we're supporting this as a content type, it would be better for the newsroom and the audience if Editions had bylines.

**Comment by sdillingham** [comment]
AC:

1) Editions have Content Byline associations, and the associated UI in Outpost.
2) Edition bylines are displayed in the front-end web views for The Short List.
3) Edition bylines are displayed in the HTML and plain text templates for the Short List email newsletter.

**Comment by Ravenstine** [comment]
@sdillingham
Where, on the views, do you think the byline should go?  Maybe an HR under the title and then the byline?
![image](https://cloud.githubusercontent.com/assets/5193330/11723286/99cd7c0a-9f22-11e5-82ad-b78a40ea1747.png)

I did see a page that already does this, but I lost track of it.  The news stories are kind of like this but their layout is different.

Also, how about displaying the bylines of the stories in each of their sections in the short list?  Is that something we care about?

**Comment by Ravenstine** [comment]
Ah, I found it.  So maybe like this?
![image](https://cloud.githubusercontent.com/assets/5193330/11723379/ff653bac-9f22-11e5-93fe-849656f9917d.png)

**Comment by sdillingham** [comment]
Yeah, I think a byline should be placed in the area you identified in your Short List screenshot. And to your other question, we don't need bylines for each of the summaries in the Short List.

**Comment by Ravenstine** [comment]
I've added the byline to both the main shortlist view as well as the email templates.  Here's the web view:
![image](https://cloud.githubusercontent.com/assets/5193330/11751082/1bc8e09a-9fec-11e5-9f1f-93ed2a851975.png)

**Comment by Ravenstine** [comment]
HTML email template:
![image](https://cloud.githubusercontent.com/assets/5193330/11752088/63ef9958-9ff2-11e5-8ec1-4fb6dc3734ca.png)

**Comment by sdillingham** [comment]
This is looking good @Ravenstine. I'd want to adjust the styling of the byline on the email to make it stand out less, but other than that the design looks :+1:
