### ISSUE TITLE
Set up square vs. simple short list CTA test in optimizely

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#342]
AC

1) There is a test of the square CTA bottom of body content vs. the simple CTA bottom of body content

Bonus AC: Test injecting the simple CTA halfway / after X number of p tags / some other consistent display method in body copy

**Comment by Ravenstine** [comment]
@vsinghkpcc Do we have existing markup for these appeals?  I'm guessing that this AC is similar to how the Short List Appeal test works...

**Comment by vsinghkpcc** [comment]
The square appeal is the one that's currently on all article pages. 

![screen shot 2015-10-08 at 11 02 19 am](https://cloud.githubusercontent.com/assets/13337277/10375135/a1e566d0-6dab-11e5-8aec-91c692fd0b53.png)

The "new" simple appeal is as outlined here: https://github.com/SCPR/design/issues/12

We want to test the same headline and sub (THE BEST SOCAL NEWS IN YOUR INBOX, DAILY. Catch up each morning with KPCC's Short List newsletter.) but A/B test the display.

If you get to the Bonus AC, we can discuss where the appeal should be injected to test.

**Comment by Ravenstine** [comment]
Experiment created here:
https://app.optimizely.com/edit?experiment_id=3619140775

Contains two variations: One with a simple design at the same spot and another of the simple design that is moved to the middle of the body.
