### ISSUE TITLE
Add events newsletter signup to events pages

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#343]
AC

1) Add an events newsletter signup to the individual events page template, using previous design used for Short List signup

Copy to use-
Hand-picked SoCal events.
Get our weekly newsletter of cool things happening around LA:

**Comment by sdillingham** [comment]
One path on this would be to duplicate this partial:

https://github.com/SCPR/SCPRv4/blob/master/app/views/shared/widgets/_short_list_subscribe.html.erb

and then update the copy, modify the subscribe form to use the correct Eloqua subscribe form.

The new partial would then just need to be included here:

https://github.com/SCPR/SCPRv4/blob/master/app/views/events/_event.html.erb

**Comment by Ravenstine** [comment]
@sdillingham @vsinghkpcc 

I've added a form which corresponds with a form added in Eloqua.  What needs to be done is styling and some re-wording of the form(I'm not good at writing headlines and descriptions).

**Comment by Ravenstine** [comment]
Design is good to go.

**Comment by Ravenstine** [comment]
@sdillingham Ship it?

**Comment by sdillingham** [comment]
:shipit: !

**Comment by vsinghkpcc** [comment]
Moved back to update the copy:

Headline: Hand-picked SoCal events
Sub head: Get our weekly newsletter of cool things happening around LA:

**Comment by Ravenstine** [comment]
@vsinghkpcc Updated with new headline and subheadline.

**Comment by vsinghkpcc** [comment]
@Ravenstine Looks good!

**Comment by sdillingham** [comment]
This is deployed - closing.
