### ISSUE TITLE
Backend work for Series

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#344]
Currently the newsroom hijacks the issues system when they want to put together a series - even though a series is a different animal than an issue. (example of a series using the issues system: http://www.scpr.org/issues/harm-at-home)

AC

1) TBD

**Comment by sdillingham** [comment]
Closing in favor of our Taxonomy work (https://github.com/SCPR/SCPRv4/milestones/Content%20Taxonomy%20Overhaul)
