### ISSUE TITLE
Validate deliverability of AdTech email ad tags in API-driven Eloqua newsletters

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#346]
Currently we push out the Short List and Breaking News email campaigns from SCPRv4 via an Eloqua API integration. Eloqua appends tracking parameters to hyperlink URLs which breaks DFP's email ad tag clickthrough function. Since we now have AdTech and it also supports email ad creative, it's worth testing to see if it is a viable alternative.

AC:

1) Create a test email campaign in AdTech.
2) Install email ad tag onto either the Breaking News or Short List HTML email template. 
3) Deploy to staging and run an end-to-end test to verify whether AdTech's email ads consistently deliver both impressions and clickthroughs across a variety of common email clients (iOS mail, Gmail, Outlook, etc.).

**Comment by sdillingham** [comment]
Here's a sample banner you can use to set up a test campaign:

http://media.scpr.org/adhost/static-assets/display-banners/short-list/300x50.jpg

**Comment by sdillingham** [comment]
Here's the spot in our current Short List template where we've hard-coded an ad; this can be replaced with an AdTech tag on your test branch:

https://github.com/SCPR/SCPRv4/blob/master/app/views/editions/email/template.html.erb#L58-L60

**Comment by Ravenstine** [comment]
The link to the simple banner gives me a 404 error.

**Comment by sdillingham** [comment]
Here's the code for the AdTech ad tag to place into the Short List template for testing:

`
<a href="http://adserver.adtechus.com/adlink/3.0/5511.1/3856755/0/711/ADTECH;key=key1+key2+key3+key4;grp=[group] target="_blank"><img src="http://adserver.adtechus.com/adserv/3.0/5511.1/3856755/0/711/ADTECH;key=key1+key2+key3+key4;grp=[group]" border="0" height="50" width="300" alt="[Alt-Text]"></a>
`

**Comment by sdillingham** [comment]
OK, a test campaign in AdTech has been created. @Ravenstine, ping me when you switch over to this task so we can step through how to run a test once the ad tag has been implemented in SCPRv4.
