### ISSUE TITLE
Documentation of Parse work for Pledge Drives

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#349]
AC

1) Create a guide for parse work necessary to support membership drives

**Comment by sdillingham** [comment]
Guide has been posted to the #pledge-free-stream channel in Slack.

**Comment by vsinghkpcc** [comment]
Work remaining: one more edit including notes from Fall Drive.

**Comment by sdillingham** [comment]
Edits added to document in Slack.
