### ISSUE TITLE
Membership Drive Thermometer

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#350]
AC

- [x] There is a design for the thermometer (@tinykb)
- [x] Coordinate with MPR to get data out of Mango (@sdillingham)
- [x] Properly fetch data from Mango (@Ravenstine)
- [x] Implement the finalized thermometer as a VWO test (@Ravenstine)

**Comment by sdillingham** [comment]
@tinykb Has been nice enough to take on this design task. Assigning to her to tackle AC 1.

**Comment by tinykb** [comment]
Thermometer mock 
![progressbar](https://cloud.githubusercontent.com/assets/14928015/10461219/35ea84de-718d-11e5-993e-cd7704c37467.png)

**Comment by sdillingham** [comment]
Here's the final approved version:

![screen_shot_2015-10-13_at_10 27 25_am](https://cloud.githubusercontent.com/assets/442483/10464573/605597a6-719f-11e5-99a0-08398850daed.png)

**Comment by sdillingham** [comment]
MPR has provided us with a data endpoint to track KPCC's fundraising progress for the current drive:

https://scprcontribute.publicradio.org/drive_data.xml

It returns a number of data points, but the only ones we care about are `drive_dollars_goal` and `drive_dollars_so_far`. You'll need the latter to display the current amount we've raised on the progress bar, and you'll need the former to do the math and figure out the percentage we've raised against our goal so we know how much progress to display on the orange bar.

We want to measure the impact the progress bar has on clickthrough, so we want to implement this as an experiment inside VWO. 50% of users will see the normal homepage, the other half will see the progress bar in place of the standard masthead elements adjacent to the logo.

**Comment by sdillingham** [comment]
@tinykb: one more task on this that will make Ben's life easier: could you work up a quick spec sheet indicating colors, font faces, sizing, etc. that will need to be defined in the css for this component? That will make front-end coding go faster.

**Comment by tinykb** [comment]
@Ravenstine: Here's some CSS context for this mock

[Thermometer-CSS.rtf | uploaded via ZenHub](https://files.zenhub.io/561d559d4e5de1c63afe7c5d)

**Comment by sdillingham** [comment]
This test is implemented.
