### ISSUE TITLE
Related Links should be unique bidirectionally

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#352]
If you take two pieces of content and on each one add a related link to the other, you'll get a duplicated Related Links display on both sides since we show both incoming and outgoing links on a piece of content.

Functionally, the arc between two pieces of content should be considered bidirectional and should only exist once. We don't do anything in the data model to enforce this, though, leading to awesome examples like this one:

http://www.scpr.org/news/2008/07/01/2551/helicopter-ride-led-dodgers-chavez-ravine/

![screen shot 2015-10-09 at 10 02 33 am](https://cloud.githubusercontent.com/assets/204350/10395804/e43efa7a-6e6c-11e5-8761-8d1748d06830.png)

We should:

* [x] Add a read-only display of incoming related links to the related content widget in the outpost editor interface
* [x] Add a data model check to prevent a link from being created if the inverse link already exists or if the incoming link is the article currently being edited
* [x] Write a code snippet to go through the existing related table and remove duplicate references

**Comment by ewr** [comment]
A quick query suggests 810 pieces of content have duplicated links attached:

```
select distinct media_related.content_type,media_related.content_id from media_related join media_related as r1 where media_related.content_id = r1.related_id and media_related.content_type = r1.related_type and media_related.related_id = r1.content_id and media_related.related_type = r1.content_type
...
810 rows in set (0.42 sec)
```

**Comment by vsinghkpcc** [comment]
Let's approach this ticket assuming AC 1 is "simple" - if we discover it's not, then let's revisit this ticket.

**Comment by vsinghkpcc** [comment]
Remaning work:

- [ ] Review
- [ ] Push live

**Comment by vsinghkpcc** [comment]
Reviewed on @Ravenstine's machine - looks good to me!

**Comment by Ravenstine** [comment]
This has been put into production.  A few days ago I deployed and there was an issue with the Gemfile not using the right version of outpost-aggregator.  Now it seems to be running smoothly.
