### ISSUE TITLE
PMP minor issue: AHP articles loading as Marketplace

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#354]
Very minor issue: American Homefront Project remote stories import into the CMS with "Marketplace" as the News Agency. Byline info for individual reporter doesn't import at all.

**Comment by sdillingham** [comment]
Another issue, tangentially related: I believe we're not successfully importing audio from the AHP articles even though audio is attached to these articles in the PMP.

**Comment by vsinghkpcc** [comment]
AC

1) The PMP importer is smarter about assigning the correct news agency for imported stories.
2) The PMP Importer is successfully importing audio for both Marketplace and AHP stories, when available.

**Comment by Ravenstine** [comment]
Just to re-clarify what I had talked about during sprint planning:

* Currently, we have the importer hard-coded to blanketly label all RemoteArticles as being from "Marketplace".
* We are also currently querying for stories based on the tag "Marketplace" and the collection ID for veterans' stories. ("4c6e24e5-484f-49e8-be8d-452cfddd6252")
* Technically, we *can* get a byline for each story, but this can either refer to the organization(e.g. Marketplace) or the name of the person who wrote it, or both at the same time.  It's not uniform and I'm pretty sure it doesn't always give us what we want either.
* The organization name may be in the array of tags that get returned with the article, but how are we to identify the correct name in the array?  The organization name does not always have the same index in the array of tags.  Hypothetically, it might be possible to keep a list of generic tags that we can eliminate.  Here are some arrays of tags from various news stories:
```
[["International", "NPR NewsMagazine-y", "News", "War"],
 ["Gay and Lesbian", "NPR NewsMagazine-y", "News", "War"],
 ["Hard Feature", "NPR NewsMagazine-y", "News", "War"],
 ["Hard Feature", "Historical", "NPR NewsMagazine-y", "News", "War"],
 ["Hard Feature", "NPR NewsMagazine-y", "News", "War"],
 ["Hard Feature", "NPR NewsMagazine-y", "News", "War"],
 ["NPR NewsMagazine-y", "News", "War"],
 ["NPR NewsMagazine-y", "News Reporting", "Public Affairs", "Science", "Technology"],
 ["Education", "NPR NewsMagazine-y", "News", "News Reporting", "War"],
 ["Hard Feature", "NPR NewsMagazine-y", "Public Affairs", "War"]]
```
Eliminating things like "News", "War", "Science", "Technology", "Education", etc., could leave us with an organization name given our list of news categories is thorough enough.  I don't know that this is really very feasible.  

A safer alternative might be to have a list of known news organization names to match by.

**Comment by sdillingham** [comment]
@Ravenstine I read through the PMP docs and agree that it doesn't make it easy to understand the common name of the entity who published the story. Just to double-check, are we sure there's nothing around `owner` or `creator` links that we can follow to get to a reliable name to plug into the "News Agency" field?

https://support.pmp.io/docs#collection-docjson-core-links

If not, then we have a little bit of a conundrum with the AHP content. We certainly could set a value of "American Homefront Project" as the News Agency for any stories coming through that PMP collection, but there are a mix of stories coming through that collection from two different public radio stations: WUNC and KUOW. I'm not sure how important it is to give specific attribution to each story, or if it's enough to    just label them all "American Homefront Project".

**Comment by Ravenstine** [comment]
@sdillingham For every AHP article that I can download, it lists "Public Radio Exchange" as both the owner and the creator.  Which is true-ish because that's where  the stories are linked(prx.org).  Not sure if this is what we want.

**Comment by sdillingham** [comment]
Huh, yeah, that's worthless. :) So then I think for now we just set up something in the importer code that maps the AHP collection to set the news source to "American Homefront Project" and the Marketplace tag sets the news source to "Marketplace."

**Comment by Ravenstine** [comment]
I'm going to jump back to this later: The first AC is done but the second one is a little more involved because while we can get the correct data that we need for the audio, it's coming in differently than the objects that we get for Marketplace.  It seems like some of our other tickets are of a slightly higher priority for today.

**Comment by Ravenstine** [comment]
This is merged and in production.
