### ISSUE TITLE
Featured Issue tags on story sidebar go nowhere

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#355]
Minor bug: Featured issue tags on individual story sidebars go nowhwere, even for issues that have been marked "featured."

**Comment by ezass** [comment]
![screen shot 2015-10-12 at 2 18 35 pm](https://cloud.githubusercontent.com/assets/994636/10439080/7899fd9c-70ec-11e5-9f7b-0bb4ae2c8f99.jpg)

**Comment by Ravenstine** [comment]
The link now directs to the actual issue page.
