### ISSUE TITLE
Improve Eloqua email campaign naming conventions 

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#357]
The way we're naming Eloqua campaigns that we create via their API is making it difficult for Jason to run monthly rollup reports around campaign performance. We'll want to adopt this naming convention for the Short List, Monday Short List, and Breaking News emails:

[ Newsletter Name YYYYMMDD ] Truncated Campaign Title

So for example:

[ short-list 20151016 ] Safety at Dodger Stadium, quake

Relevant code is here:

https://github.com/SCPR/SCPRv4/blob/84bfa97f2ecabea6d70716820951a5a89747375b/app/models/edition.rb#L124

https://github.com/SCPR/SCPRv4/blob/84bfa97f2ecabea6d70716820951a5a89747375b/app/models/edition.rb#L138

https://github.com/SCPR/SCPRv4/blob/master/app/models/breaking_news_alert.rb#L157

**Comment by Ravenstine** [comment]
This has been merged and deployed.  If something goes wrong(which I doubt), we can certainly re-open it when the time comes.
