### ISSUE TITLE
Turn KPCC Plus web player off outside of drives

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#361]
AC

- [ ] KPCC Plus web player is "turned off" in a way that doesn't break the experience for a user.

**Comment by vsinghkpcc** [comment]
Notes:
- Vijay will provide copy for messaging
- Use alternate template to message to user "Drive over, KPCC Plus no longer available"

**Comment by vsinghkpcc** [comment]
#Sorry, KPCC Plus is Off-Air

##We aren’t in Membership Drive mode right now.

Not to worry - simply [visit the Listen Live page] to hear the normal programming you know and love.

If you are a current member, we’ll e-mail you a link to access KPCC Plus again during our next drive. For more information about KPCC Plus, please visit the FAQs page.

Happy listening!

**Comment by Ravenstine** [comment]
The pledge free stream has been turned off and replaced with a message page.  Error page is no longer a Flatpage.
