### ISSUE TITLE
Podcast and On-Demand Audio Contexts Should Match

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#364]
We use the `context` query param to assign audio to shows in our audio analytics. For podcasts, that comes from the podcast slug. For on-demand, that comes from the KPCCProgram or ExternalProgram slug.

Those don't always match right now, which means we get podcast plays for "loh-down" but on-demand plays for "loh-down-on-science".

In order to unify our analytics, we need these slugs to match. Renaming podcasts (or programs) probably isn't a workable answer, but it may be sufficient to simply use the slug of the attached program (if available), rather than the podcast's slug.

**Comment by Ravenstine** [comment]
@ewr From what I can tell, loh-down-on-science is the only podcast that has a different slug.

Do we want to have podcasts that are from KPCC use the slug from their related KpccProgram, or should we just rename the one podcast with the wrong slug?

**Comment by ewr** [comment]
There are definitely others. For instance "5EW" (program) vs "5-every-week" (podcast)...

**Comment by Ravenstine** [comment]
Weird, for me those both seem to match.

**Comment by Ravenstine** [comment]
`Programs.all.map(&:slug)`

```
airtalk
patt-morrison
filmweek
loh-down-on-science
loh-life
offramp
street-stories
marc-haefele
business-update-with-mark-lacter
pacificdrift
town-hall-journal
storycorps
titlewave
comedy-congress
ask-the-chief
big-man-on-campus
filmweek-marquee
eatla
madeleine-brand
offramp-extra
take-two
brand-martinez
take-two-evenings
first-person
reveal
the-frame
citycast
wheel-thing
welcome-to-vinci
5EW
tuesday-reviewsday
the-brood
the-mash-up-americans
```

`Podcast.all.map(&:slug)`

```
loh-down-on-science
offramp
dinner-party-download
filmweek
loh-life
airtalk
patt_morrison
street-stories
business-update-with-mark-lacter
marc-haefele
filmweek-marquee
take-two
drucker-on-the-dial
news
i-love-la
brains-on
the-frame
citycast
the-frame
bike-curious
wheel-thing
welcome-to-vinci
5EW
tuesday-reviewsday
the-brood
the-mash-up-americans
```

**Comment by Ravenstine** [comment]
Yeah nevermind, I fooled myself.

Program Slugs:
```
airtalk
patt-morrison
filmweek
loh-down-on-science
loh-life
offramp
street-stories
marc-haefele
business-update-with-mark-lacter
pacificdrift
town-hall-journal
storycorps
titlewave
comedy-congress
ask-the-chief
big-man-on-campus
filmweek-marquee
eatla
madeleine-brand
offramp-extra
take-two
brand-martinez
take-two-evenings
first-person
reveal
the-frame
citycast
wheel-thing
welcome-to-vinci
5EW
tuesday-reviewsday
the-brood
the-mash-up-americans
```

Podcast slugs:
```
loh_down
offramp
dinner-party-download
filmweek
loh_life
airtalk
patt_morrison
street-stories
business_update
marc-haefele
marquee
take-two
drucker-on-the-dial
news
i-love-la
brains-on
the-frame
citycast
the-frame-segments
bike-curious
wheel-thing
welcome-to-vinci-a-podcast-about-true-detective
5-every-week
tuesday-reviewsday
the-brood
mash-up-americans
```

Differences:
```
loh_down
dinner-party-download
loh_life
patt_morrison
business_update
marquee
drucker-on-the-dial
news
i-love-la
brains-on
the-frame-segments
bike-curious
welcome-to-vinci-a-podcast-about-true-detective
5-every-week
mash-up-americans
```

Of course some of those don't have KpccPrograms.  But yup, there are a bunch.
