### ISSUE TITLE
Need a Periodic Job to Review Schedule Occurrences for Overlaps and Gaps

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#370]
Over the weekend, a gap at the time of the time change caused iPhone app clients to attempt to DDOS the website using schedule endpoints. While the iPhone app schedule logic is a bug, this would have been avoided had we recognized the gap ahead of time.

AC

- [ ] We need a periodic (daily?) job that reviews the upcoming schedule to identify overlaps and gaps and emails a warning to the correct parties.

NOTE: Vijay will help identify correct parties, and those people will be in an e-mail group

**Comment by Ravenstine** [comment]
@vsinghkpcc Is there a specific email group in Eloqua that I should have this job send notifications to? (or if not, who should we include in an email group?)

**Comment by vsinghkpcc** [comment]
Submitted a request this morning for a new e-mail group to send this notification, just waiting to hear back...

**Comment by vsinghkpcc** [comment]
@Ravenstine We have the e-mail group: digitalbroadcastopsscpr@scpr.org
