### ISSUE TITLE
Improve Segment Performance

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#371]
AC

- [x] When things in segments change that don't affect our stuff, redo associated expensive things less often
- [x] On segment pages, cache "recently" based on the program object instead of the segment object

**Comment by ewr** [comment]
Biggest single win may be in nested caching in the featured_programs partial, which currently gets no caching and appears to add ~40ms-80ms.

**Comment by Ravenstine** [comment]
![image](https://cloud.githubusercontent.com/assets/5193330/11700890/63ca8ef0-9e81-11e5-8d80-fac077c4de64.png)

Here is a screenshot that shows the effect after deploying these changes to the featured_programs partial.  This represents the reduced time spent with MySQL(yellow) and the featured_programs partial(green), which both thin out.
