### ISSUE TITLE
Search in "Remote Articles" doesn't work

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#377]
typing a term into remote articles' search results in an error message

**Comment by ezass** [comment]
![screen shot 2015-11-06 at 10 02 57 am](https://cloud.githubusercontent.com/assets/994636/11004693/a3a47cc0-846e-11e5-87b4-5cb0bb2d4b21.jpg)
![screen shot 2015-11-06 at 10 02 50 am](https://cloud.githubusercontent.com/assets/994636/11004697/a763a32c-846e-11e5-8c03-35c083b55020.png)

**Comment by sdillingham** [comment]
Updating the issue title to reflect that this search of Remote Articles is a feature that was never implemented in SCPRv4.

**Comment by vsinghkpcc** [comment]
AC

- [ ] Remote articles are searchable in outpost

**Comment by Ravenstine** [comment]
@sdillingham 

Pull request mentioned above.

A demo of the search is on staging:
http://scprv4-staging.scprdev.org/outpost/remote_articles

What do you think?

**Comment by sdillingham** [comment]
@Ravenstine I reviewed both the PR changes and the functionality on staging and it looks good.

**Comment by sdillingham** [comment]
I think my final question is just about the impact of indexing an additional ~30k records to ES. @ewr any impacts either in terms of initial indexing or general ES resource consumption?

**Comment by ewr** [comment]
Zero.

**Comment by Ravenstine** [comment]
@ezass Remote articles are now searchable.
