### ISSUE TITLE
Refine Tag Implementation

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#381]
- [x] Remove "is_featured" attribute from Tag model/Issues controller + view, plus outpost filters and forms
- [x] Add `tag_image` attribute (maybe just use asset ID field like we do in Bios?)
- [x] Add `tag_type` attribute with three values ("beat", "series", "keyword").
- [x] Add Outpost UI to support groupings of tags by type in the tag dropdown.
- [x] Delete "Issues" layout and have issues use "Ronin" layout
- [x] Add "parent entity" attribute to Tag model. Allow KPCC Programs to claim tags that belong to them.

**Comment by Ravenstine** [comment]
Will `tag_type` be a required field or have a default value?

**Comment by sdillingham** [comment]
Good question - it should be required for sure, and I think "Keyword" is the right default value. "Series" and "Beat" are tag types that have greater implications for the design and front-end experience, so I think Outpost users should have to be more intentional about selecting those.

**Comment by Ravenstine** [comment]
`Add Outpost UI to support groupings of tags by type in the tag dropdown.`

I am trying to envision how this would be implemented.

The simplest solution I can think of is to add the grouping name between brackets `i.e [series] Higher Education` to the dropdown search so that a person can search by grouping and/or the name of the tag.  It would also let them see the grouping type along with each tag.

But I'm guessing we have something else in mind?  Maybe multiple columns?

**Comment by sdillingham** [comment]
I think we keep it simple. Select2, the jQuery plugin Outpost depends on for its dropdown functionality, has the ability to transform <optgroup> collections in a standard <select> element and create headings out of them:

https://select2.github.io/examples.html#single

I think that's sufficient for an MVP.

**Comment by Ravenstine** [comment]
:+1:

**Comment by Ravenstine** [comment]
@sdillingham As far as programs having ownership of tags, do we need the ability to have tags belong to multiple shows or is it fine to just give tags a foreign key to a program(i.e. program has many tags, tag has one program)?

**Comment by sdillingham** [comment]
I think @ewr had the idea to make this a polymorphic association so that we have an interface that any other model can use to be a parent entity for tags (correct me if I'm wrong). We'd start with KPCCPrograms, but we want the flexibility for other models to act as parent entities in the future. 

I'm in favor of tags only being able to have a single parent entity. I think things will get confusing if a series could belong to multiple parent entities, and I think it's unlikely that we'll need that capability.

**Comment by Ravenstine** [comment]
Awesome, that's the direction I started taking. :)
