### ISSUE TITLE
Revise Taxonomy

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#382]
- [x] Populate "beat" tags for each of the regional desk beats.
- [x] Migrate all stories categorized as Immigration to a tag and delete the Immigration Category from the DB and instances of the site nav.

**Comment by Ravenstine** [comment]
@sdillingham Do we have a list of these beat tag names?

**Comment by sdillingham** [comment]
Yep, here they are:

* Public Safety
* SoCal Economy
* SoCal Politics
* The Social Safety Net
* Vets
* Workplace
* Changing Neighborhoods & Affordability
* Communting
* Immigration 3.0
* Infrastructure
* Orange County

**Comment by Ravenstine** [comment]
I'm assuming that I can make up the slugs for these.  I will probably need descriptions for each of them at some point too.

**Comment by sdillingham** [comment]
Yeah, descriptions can come later. Here's slugs you can use:

public-safety
socal-economy
socal-politics
social-safety-net
vets
workplace
changing-neighborhoods
communting
immigration
infrastructure
orange-county
