### ISSUE TITLE
Verticals: Unable to add source story to featured quote

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#387]
On the vertical pages, in the section where we post the featured quote, the chooser that used to allow us to link that quote to a story appears to have disappeared. Was this intentional? 
![screen shot 2015-11-20 at 3 17 27 pm](https://cloud.githubusercontent.com/assets/994636/11314560/7e015cda-8f9b-11e5-9b8f-7173dcac09d4.jpg)

**Comment by sdillingham** [comment]
I'll investigate and post a comment later tonight or tomorrow.

**Comment by sdillingham** [comment]
Looks like a javascript error is preventing the Outpost Aggregator from loading in this view. I suspect this is an unintended consequence of our bidirectional link work here: https://github.com/SCPR/SCPRv4/pull/362. Looping in @Ravenstine and @vsinghkpcc so we can prioritize and address the issue.

**Comment by Ravenstine** [comment]
I checked out that error, but I don't think that's the primary cause.  I seem to be getting a `401 unauthorized` error for the following url:

`http://www.scpr.org/api/private/v2/articles?limit=10&page=1`

Despite being on the same domain and logged into Outpost.  I'm not yet sure what's causing that.

**Comment by Ravenstine** [comment]
@ezass The UI for adding a source story is back.
