### ISSUE TITLE
Need to support DAAST Format for Ad Response

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#396]
Currently ads use an overloaded VAST for audio. We're working on switching our ad infrastructure over to DAAST, which is similar but designed for audio. 

Current ad parsing implementation is here:

https://github.com/SCPR/SCPRv4/blob/8f02a64b3905e8b94fb8db4c4c81f03437653b15/app/assets/javascripts/listen_live.js.coffee#L116-L164

I'm not sure if there's a way to reuse StreamMachine's ad parsing code (also written in Coffeescript), but it's here: 

https://github.com/StreamMachine/StreamMachine/blob/2d819379fa2cdc9505d9c3cc20663b0731d68be5/src/streammachine/slave/preroller.coffee#L234-L328

* [x] Preroll should parse and handle either VAST or DAAST responses, without knowing which one it will receive.
* [x] Preroll should support multiple impression URLs, as allowed by the spec.
* [x] Preroll should correctly hit the companion ad's creativeView tracking URL when creative is displayed.

**Comment by ewr** [comment]
Test preroll endpoint is:

http://adserver.adtechus.com/?adrawdata/3.0/5511.1/3683959/0/1013/header=yes;cookie=no;adct=text/xml

There should always be a dev campaign running.

**Comment by ewr** [comment]
Actually, if the display is using the html version of the companion ad, creativeView should already be covered via a `display:none` image. Take a look at the XML response and you'll see what I'm talking about.

**Comment by Ravenstine** [comment]
@ewr It looks like the test endpoint you posted disappeared somehow.  Can you re-add it?

**Comment by ewr** [comment]
Works for me...

**Comment by Ravenstine** [comment]
I've been reading the DAAST spec.  For clarity, are we essentially wanting to do the same thing with both the impression URLs and the creativeView tracking URL?  It seems like all we need to do is just touch them.

Also, between lines 58 and 64 in listen_live.js.coffee, it appears like we have some commented out code that is intended to do the touching for a single impression URL:
```coffee
                if url = @_impressionURL
                    @_impressionURL = null
                    # create an img and append it to our DOM
                    img = $("<img src='#{url}'>").css("display:none")
                    @_live_ad.append(img)
                    #$.ajax type:"GET", url:"#{url};cors=yes", success:(resp) =>
                        # nothing right now
```

If we are expecting multiple URLs, how do we want to handle the portion where an image is being added to the DOM?  Do we want to add one for each impression URL?

**Comment by ewr** [comment]
For any impression / event URL, the client just needs to fire a request. It doesn't need to worry about the result.

The commented out AJAX call can be deleted. That was from before the image code was added. Browsers weren't consistently allowing the AJAX call to fire, and the image tag (even with `display:none`) seemed to reliably allow the call to be made.

Correct, if there are multiple impression URLs, you would just want to inject one image tag per impression URL.

**Comment by Ravenstine** [comment]
@ewr Would you suggest following the same approach for the creativeView tracking URL?  My first instinct would be to use AJAX but if an image tag works more consistently then I'd do it that way instead.

**Comment by ewr** [comment]
See my comment above about creativeView. That should actually be covered just by using the HTMLResource (which contains an image tag hitting the creativeView event). That's one we have to handle explicitly in the apps, but on the web you just get it for free.

**Comment by ewr** [comment]
FWIW, here are some stripped-down test ad files that might be helpful for seeing format:

https://github.com/StreamMachine/StreamMachine/tree/master/test/files/ads

**Comment by Ravenstine** [comment]
In both that test URL and the example XML file from StreamMachine, the image tag in the DAAST response does not appear to have `display: none` set.  This differs from the VAST version, which has that style set.

This is resulting in a "broken" image next to the banner:
![image](https://cloud.githubusercontent.com/assets/5193330/11986692/6444869a-a987-11e5-94b7-b9581d547a50.png)

Maybe this is something we'll have to manually add `display: none` to?  I'm uncertain why it wouldn't just come with it, unless there's something not set properly.

**Comment by ewr** [comment]
We'll just need to fix that in our template on the adtech side.

**Comment by Ravenstine** [comment]
@ewr I would appreciate feedback you have for the review PR above if you have any. :point_up:
