### ISSUE TITLE
Minor issue: Preview function sometimes not loading slideshows & videos

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#399]
I've heard from a few different people (most recently Oscar Garza) that the preview function frequently doesn't load slideshows. I've seen this a few times in stories I've worked on as well. Obv. not a huge issue.

**Comment by sdillingham** [comment]
Adding another symptom to this ticket: lead video assets aren't previewing correctly in Outpost either. Instead of the video embed you just get a static image asset.

**Comment by Ravenstine** [comment]
@ezass Can you provide me an example or two of where this is happening?  I've tried about a dozen news stories that have a slideshow or a video and haven't reproduced the problem.

**Comment by Ravenstine** [comment]
I'm going to put this one to rest, unless we find out otherwise.  It seems like this may have been a fluke, perhaps in getting a failed connection to AssetHost or a CDN or something.

**Comment by Ravenstine** [comment]
This appears to happen when you add this asset to a ShowSegment and treat it as a video:
http://a.scpr.org/a/assets/121718

I don't know if this happens with other videos, but it's likely.

The video shows up fine on the live page and only fails in preview.  I've narrowed the issue down to the #render_asset helper method.  If passed an actual model instance, the problem goes away, if passed an Article, the video doesn't work.
