### ISSUE TITLE
Remove "Voices You Know" Element

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#400]
AC: The "Voices You Know" element has been removed from the site

Relavent Code:
https://github.com/SCPR/SCPRv4/blob/1cef4b302e539fc79efa4625469dbe1cb69295eb/app/helpers/application_helper.rb

https://github.com/SCPR/SCPRv4/blob/84bfa97f2ecabea6d70716820951a5a89747375b/app/views/shared/masthead/_layout_header.html.erb

https://github.com/SCPR/SCPRv4/blob/84bfa97f2ecabea6d70716820951a5a89747375b/app/assets/stylesheets/masthead.css.scss

**Comment by sdillingham** [comment]
@Ravenstine It would be good to remove the image assets themselves (at `app/assets/images/personalities/`) as a cleanup step.

**Comment by Ravenstine** [comment]
@sdillingham Yes.  And that's another step I should add to my list.
