### ISSUE TITLE
Badge should not increment when pushing breaking news alerts to 

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#402]
Related to https://github.com/SCPR/KPCC-iPhone/issues/118.

This can be addressed in SCPRv4 in our Breaking News Alerts model. Currently we have a single `publish_mobile_notification` method that manages pushes for all our native apps, and is set to increment the badge in all cases:

https://github.com/SCPR/SCPRv4/blob/master/app/models/breaking_news_alert.rb#L119

I think the right way forward would be to not increment the badge when the `alert_type == audio`. Neither the iPad nor our phone apps have a good way to act on  badges for Live Stream events, so it makes sense to differentiate push behavior based on the type of push we're sending, rather than specifying different push behaviors per app.

**Comment by vsinghkpcc** [comment]
Note: Any existing badge numbers should be cleared out.

**Comment by Ravenstine** [comment]
@vsinghkpcc @sdillingham I may be mistaken, but I do not see any Breaking News Alerts in Parse with the `audio` type.  If that's accurate, maybe nothing needs to be cleared out?

**Comment by sdillingham** [comment]
I believe we're mapping the `audio` type we store in the database to a value of "Listen Live" when we push to Parse:

https://github.com/SCPR/SCPRv4/blob/master/app/models/breaking_news_alert.rb#L22

**Comment by Ravenstine** [comment]
Is there a permission that I need to edit the badge of an alert in Parse?  I am logged in with the `iphonedev@scpr.org` account, but can't seem to make any changes to push notifications.
