### ISSUE TITLE
Contentshells don't appear to allow images 

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#404]
The pop-up asset chooser appears to have disappeared in content shells: http://www.scpr.org/outpost/content_shells/630/edit

Screenshot attached.
![screen shot 2015-12-28 at 10 33 03 am](https://cloud.githubusercontent.com/assets/994636/12023458/8bbec51c-ad4e-11e5-86c1-565a822f21af.png)

**Comment by Ravenstine** [comment]
@ezass @ewr It looks like the body input is not showing up, although I don't see a stand-out cause for this.  I'll take a closer look and see if I can figure this out today.
