### ISSUE TITLE
CA Counts: Stories from Outpost into PMP

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#406]
AC

- [x] Research specs for pushing our content to PMP
- [x] Stories from Outpost are available in PMP
- [x] An editor can decide what's pushed to PMP
- [x] PMP permissions default to "public" but there is a mechanism to set more fine-grained permissions when necessary

**Comment by Ravenstine** [comment]
Comment from Planning: What is supposed to happen if a story needs to be edited?  i.e. Does a story that is edited also get updated in PMP?

**Comment by Ravenstine** [comment]
:point_up: Indeed, it seems like we can do this.

https://github.com/publicmediaplatform/pmpdocs/wiki/Saving-Documents-With-an-SDK

**Comment by Ravenstine** [comment]
@ewr Would I be correct in assuming that we should have a `pmp` boolean on our news stories and have a job that can publish/edit the stories to pmp if that boolean is true and if the story is marked as published in our CMS?

**Comment by sdillingham** [comment]
@Ravenstine - jumping in here, yes, I think we'll need to give CMS users the ability to set flags on a per-story basis indicating stories they want to publish to the PMP. Similar to our breaking news alerts model, I think we'll also want a flag to indicate when the story has been successfully pushed to the PMP.

Also, it would make sense to implement this against all of the models that house content we might want to push to the PMP, which is more than just news stories. At minimum we should include:

* NewsStory
* BlogEntry
* ShowSegment

In the case of Blog Entries and Show Segments, we can make use of the PMP's Collection Links to set the story's property to either the blog or program it's associated with.

You could also make the case for these additional models:

* Event
* ShowEpisode

but these come with some extra considerations and are "nice to have;" the other three models above would make for a good for a first release.

**Comment by sdillingham** [comment]
One final thought: you may have already anticipated this, but it would make sense to also store a reference to the PMP document (probably the GUID) on our content models.

**Comment by Ravenstine** [comment]
:point_up: Yeah, perhaps that could even have a double-purpose of acting as a flag for being successfully published to PMP.

**Comment by ewr** [comment]
Looking through the PMP docs, creation of a GUID is a step that happens before you attempt the publish.  The GUID is definitely something that we need to attach to the content object, but a notion of publish operations and their success or failure may be separate. It looks like you have to register a callback URL to get notification of whether the publish actually succeeded. 

I would argue that any model participating in ContentBase should get this functionality, even if not all of those types actually make sense for publishing at the moment. Showing / not showing the option on the CMS could be a separate question per-type. Effectively that's the types @sdillingham named, plus ContentShell.

Rather than adding pmp fields to each content model, it would seem to make sense to let this live in its own related model. We definitely want the GUID, and perhaps a most-recent successful publish date, but I'm not sure if there are other PMP bits that are worth noting (its own audit log of publish attempts/success/failure?).

Going a little more meta: Are we uploading image assets attached to the stories, or just the text? Are we creating a group with permissions, or just uploading this content publicly?

**Comment by sdillingham** [comment]
Making this a ContentBase feature makes sense, and the idea of a separate model is better than my original suggestion. 

Editorial will want images to be uploaded along with stories, but that means having to worry about rights issues, which I worry is a bit of a Pandora's box. Do we simply check for the presence of "KPCC" in the `asset owner` attribute and only upload those images?

Permissions also potentially complicates the implementation. Let me check with Eric Z. to find out what the requirements are from editorial in terms of rights/permissions.

**Comment by sdillingham** [comment]
I'm in conversations with Eric Z. and Alex about both the image and permission questions. Will circle the wagons and report back ASAP.

**Comment by sdillingham** [comment]
Regarding permissions: the newsroom's short term goal with the CA Counts stories is to only share them with our specific partners (KQED, Capital Public Radio, KPBS). So we will need to account for permissions somehow in this issue (I've updated the AC above).

Given that it's unclear how much KPCC intends to publish to the PMP beyond this project, I'd prefer not to build a full-blown UI into Outpost for selecting permission groups on a per-story basis, though that's certainly one implementation I could envision.

Another possible approach: allow tags to be associated with a set of PMP permissions. When a story is flagged to publish to the PMP, we default to "public" permissions and override with more fine-grained permissions only if the story has an association to a tag that has a set of PMP permissions associated with it.

**Comment by Ravenstine** [comment]
Did we find out if we need to restrict the images what we include in our PMP docs?

**Comment by sdillingham** [comment]
Yes, we'll need to only pass through images to the PMP that we're certain we have rights for. Effectively, the Asset Owner attribute needs to contain "KPCC" or we don't send it on to the PMP.

**Comment by Ravenstine** [comment]
PMP also has an `episode` profile, which seems to be basically the same as `story`, just it differentiates.  This would work for our show episodes, but what about show segments?  Should we create our own `segments` profile?  Or should we just make them all stories?

**Comment by ewr** [comment]
In the context of us passing content to a partner, I think content is just content. I would think we would want that if we were publishing episodes with segments, but not when we're just publishing content in standalone pieces.
