### ISSUE TITLE
Backend adjustments for better breaking news alerts in apps

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#409]
AC
- [x] An approach for setting up breaking news alerts / schedule updates in outpost is defined and the newsroom is ok with the defined approach
- [x] The adjustments have been made in outpost
- [x] API updated to include additional data ("start time", "end time", "Should rewind", "bypass pre-roll")
- [x] Payload updated to include additional data
- [x] The backend has a way to notify clients when a breaking news alert ends

**Comment by sdillingham** [comment]
Are we tracking the changes we'll need to make to the API and our Parse pushes in a separate ticket, or should those be part of the AC for this ticket as well?

**Comment by Ravenstine** [comment]
Would I be correct in assuming that there will be no such concept as a "recurring rule" for breaking news alerts?  Of course it may be obviously contradictory, but I want to make sure my understanding is in line with what needs to be accomplished.

**Comment by sdillingham** [comment]
No, there is no concept of recurrence for breaking news alerts. Also, in sprint planning we discussed our options, and decided not to create schedule occurrence objects as part of how we solve this problem. The idea is to add attributes to the Breaking News model only; it will be up to the client (e.g. the iPhone app) to take the metadata passed in a breaking news alert and do what needs to be done to treat it like a schedule occurrence in the UI.

**Comment by Ravenstine** [comment]
:+1:

**Comment by Ravenstine** [comment]
NOTE: Currently need to figure out whether or not we need to prevent the silent pushes from going to Android devices.
