### ISSUE TITLE
CA Counts: Stories in the PMP - Push to production

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#416]
AC

- [x] Add GUIDs to document in PMP
- [x] Deploy to production
- [x] QA with a partner to verify a sample story was delivered correctly

**Comment by Ravenstine** [comment]
NOTE: In order to get started on this, I will need credentials for writing to PMP.io. (right now, I only have ones for reading)

**Comment by Ravenstine** [comment]
STATUS UPDATE: A story titled "California Counts: Demographics changing in Watts, but challenges familiar" has been successfully received by a partner through the PMP.  They are still "testing".  We might want to wait for at least one other partner to test it before we close this ticket.

**Comment by vsinghkpcc** [comment]
Closing as we met the AC for this ticket - will create other tickets if we get any specific issues reported from partner stations.
