### ISSUE TITLE
Homepage: Determine Strategy for Asset "Scoring"

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#417]
AC: 
- [x] We have better understanding of newsroom requirements
- [x] We have a proposed strategy for determining how to display assets on the homepage

**Comment by sdillingham** [comment]
Had a meeting with Product and Editorial on 2/9 to explore possible solutions for automation. Wrote up a post on Slack outlining what signals we might look at to infer asset quality, which seems possible but also steep in terms of technical effort. 

The consensus was that we should start with manual asset selection on the homepage and then evaluate whether the production workload is enough of a burden for editorial that we should invest in automation.
