### ISSUE TITLE
Allow episode rundowns to use any contentbase content

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#432]
AC

- [x] Episode rundowns can use any contentbase content

**Comment by Ravenstine** [comment]
@sdillingham So it wasn't too big a deal to get Rundowns to support other contentbase content, but I was foolish enough to not ask the question of whether or not this ticket implies displaying this support on Episode pages.  Is that something I should do?

**Comment by sdillingham** [comment]
Yeah, we should have been more explicit with the AC. Once a rundown is able to contain anything from across contentbase, then you'll need to make sure they render  properly in a bunch of places. Off the top of my head:

* Episode Pages
* Program Landing Pages (which display the latest episode and everything in its rundown
* Segment Pages (which display the episode rundown after the segment body)
* Homepage Broadcast Bar (when the current program on air is a KPCC program where `is_segmented` is true, users can click on the Program Title and get a modal window with the episode rundown)
* The Program, Episode and Schedule endpoints on our API (both V2 and V3)

**Comment by Ravenstine** [comment]
So I've worked displaying all rundown content on those pages, though I am not certain where we would be including them in the Program and Schedule endpoints, considering that we currently aren't returning segments or even episodes from those endpoints.  What might the rules be for delivering rundown content for those two endpoints?

**Comment by sdillingham** [comment]
@Ravenstine you're right, the Schedule and Program endpoints aren't in play for this feature. My bad.
