### ISSUE TITLE
QA Changing default timezone to UTC

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#433]
AC

- [ ] Changing default timezone to UTC does not break the application 

See: #424

**Comment by Ravenstine** [comment]
Just to kind of relay from other discussions around this:

I deployed the pull request to staging and did some investigating.  The places that I looked at in particular are the `home_controller` where the schedule occurrences are grabbed for the broadcast bar, and the `edition` model where it makes the decision to send the *monday* short list.  I tested the logic in both by hand on the staging server and found nothing wrong.  

I am still feeling wary of this, however.  At some point in this sprint, I'll come back to it and see if there's anywhere else that can be impacted by this change.

**Comment by vsinghkpcc** [comment]
Given that implementation would not directly produce any user wins, yet there is a level of uncertainty of what deploying to production would mean, let's keep this one in the backlog for now.
