### ISSUE TITLE
Thoughts around making Content Base content more manageable

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#440]
Here's a good example of why the current implementation can get a bit mangy: Various controllers and models need specific knowledge of what models are considered `content base`, and some have their own implementation of how these models are defined.  Multiple relationships also get complicated, like with allowing Episodes to have multiple types of content as rundowns, because all of these relationships need to be defined and set explicitly, even if they represent the same concept(i.e. Articles).  The fact that all these content base models can be represented at an `Article` also puts into question the need for an `Article` class at all.

I'm wondering if it would be a worthwhile idea to unify content under the `ContentBase` umbrella into a single table with all the columns that `Article` currently supports, and make behavioral decisions in specific models that are scoped to the content type.  In theory, any type of content can be associated with any other content, and it's just a matter of asking a content model what we want from it at a given time(e.g. all content can have child content and belong to parent content, but an Episode would have the specific behavior surrounding its Segments).  

In the long run, I think this could mean touching the database structure much less whenever we make decisions like changing the associations between content types.  Allowing `news_stories` to be associated with an `episode` could become as simple as simply including news stories in the aggregator list.  It would also mean being able to retrieve all related content when we don't necessarily need specific behavior for each content type(e.g. when we want to add new content types to a view without needing to alias attributes, change column names, or add new attributes to every `#to_article` method.

The `Article` concept doesn't particularly help because, if the above scenario required that objects in a collection have a `published_at` attribute, that attribute would need to be applied to every `#to_article` method for every Content Base model.  Is this really easier than just making sure that these models have the attributes that we are [more and more often] expecting from all of them?

An example for how our unified table might look:
```ruby
  create_table "content", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.string   "content_type"
    t.string   "headline"
    t.string   "short_headline"
    t.string   "summary"
    t.text     "teaser",           limit: 65535
    t.text     "body",             limit: 65535
    t.string   "slug"
    t.string   "news_agency"
    t.string   "source"
    t.string   "byline"
    t.integer  "status"
    t.integer  "size"
    t.integer  "duration"
    t.integer  "position",                       default: 0
    t.integer  "parent_id"
    t.integer  "parent_type"
    t.boolean  "featured",                       default: false
    t.boolean  "from_pij",                       default: false
    t.integer  "feature_type_id"
    t.integer  "asset_display_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.datetime "published_at"
    t.datetime "air_date"
  end
```
Any more complicated associations(like having a Segment belong to multiple Episodes as a rundown) would be handled through a join table.

A blocker to this is figuring out a way to make content continue to be searchable as it currently is.  If we were to merge tables, existing IDs would have to be made non-unique and/or stored in a different column(so that current URLs still reference the same content).  Alternatively, the tables can remain the same but their column names are unified.  Either way, in theory, ContentBase wouldn't need to change much so long as our models behave almost exactly like an `Article`.

This is just a half baked thought for how we might be able to make things simpler for us down the road.  Any alternative thoughts around improving Content Base would be great.

**Comment by sdillingham** [comment]
@Ravenstine this need to arrive at a more unified concept of content models across SCPRv4 is something we've been talking about since 2013. We haven't had the time to plan and execute this change, but I see it as a key part of our technical debt and unification of content models is definitely the way forward.

This is a BIG change, with lots of implications. We have backlog grooming this afternoon, and I think this would be a great topic for discussion.

**Comment by Ravenstine** [comment]
Oh yeah, and let's also consider doing the same thing with ShowEpisodes/KpccEpisodes/ExternalEpisodes and think about unifying them because, surprise, they have their own Article(i.e. Episode).  There's also a some logic branching around displaying kpcc/external episodes that we might not need.

**Comment by vsinghkpcc** [comment]
AC
- [ ] At a very high level, determine a desired architecture.
- [ ] There is a documented technical plan for making Content Base content more manageable that exposes a reasonable first next step.
(Can we make incremental changes? Or do we put other feature development on hold while we do this work etc.)

**Comment by sdillingham** [comment]
Before I forget, one more thought to add to the mix: 

One of the big pain points with our current implementation is how ugly/non-performant our front-end gets when we have to render views that cut across multiple content models. We already index and denormalize content into ElasticSearch for a bunch of reasons; it's worth considering further leveraging ES to denormalize articles into a more performant layer of the app stack. You'd then need to rewrite your front-end to query ES instead of ActiveRecord when working with content. 

The idea here would be to improve performance and simplify how we interact with content on the front-end, but preserve any potentially advantageous DB normalization on the back-end. You would wind up with an app where you content writes are  normalized/relational canonical data, but your content reads are denormalized/document-based data.

**Comment by Ravenstine** [comment]
We had a meeting where we floated some ideas around this ticket.  Here are some thoughts we had:

* Single Table Inheritance
* Articles table that content types relate to
* Use a document store(e.g. MongoDB)
* Alter ContentBase to take relationships into account

Because the ROI seems distant and possibly slim for those ideas, we decided that I will go ahead and inventory ContentBase and the Article class; figure out exactly what they are doing and how they relate to each other so that we can better understand their roles and make a decision on a move forward later on.  Concurrently, I will investigate if ContentBase and/or Article can be made to be more performant without necessarily doing a complete overhaul as our other ideas suggest.

**Comment by Ravenstine** [comment]
My thoughts, so far, surround adding indexing extra information into ES so that we don't have to do so many original_object calls.  Already, we are actually indexing most Article attributes, such as headline and body, but there are some things like Related Content which could be included as a list of titles, short headlines, and links.    That's just one example.  I think it might be possible to make such changes so that our templates only ever expect an Article and we'd have to think carefully in the future before including original objects(which is a poor practice that I myself have perpetuated).  

While I think there's still some model consolidation that we can do, I think that making an "update" to ContentBase would be a good first step so we can actually continue using ES as a document store.  To me, ContentBase and Article are both necessary but we sometimes don't use them quite right.

**Comment by Ravenstine** [comment]
I'm going to put this to rest and I've made a ticket that contains something actionable for this next sprint.  If, when Sean comes back, we discuss this again and come to a new conclusion, we can re-open this.
