### ISSUE TITLE
Continued PMP Work

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#457]
AC: We can push links to Broadcast audio and scripts as text via Outpost to the PMP according to CapRadio's spec.

This includes the work that I mentioned at demo involving making changes based on our collaboration with partner stations.  It also looks like there's yet another PMP feature that I'll be brainstorming with Eric Z today.  The estimate that is currently on this ticket is based on the amount of work that I have put in so far from this last sprint and beyond.

**Comment by sdillingham** [comment]
Regarding broadcast content in PMP: KQED has offered to post in the Slack #techchat channel and offer a proposal for how to structure broadcast audio and scripts. We'll want to weigh in on Slack to :+1: :-1: their approach, then move to implementation once we have consensus among partner stations.

**Comment by Ravenstine** [comment]
Changing this from a **1** to a **0.5**.

**Comment by vsinghkpcc** [comment]
Revised AC for Sprint 22:
- [ ] Implement Broadcast Content model in SCPRv4
- [ ] create relationships between Broadcast Content and Article Models
- [ ] Broadcast Content associated to an Article is passed to the PMP according to agreed upon schema (with partner stations)

**Comment by vsinghkpcc** [comment]
Moving to backlog until we have an agreed upon schema from partner stations.

**Comment by vsinghkpcc** [comment]
Here's the spec CapRadio outlined: https://docs.google.com/document/d/1WMLvwqCwCdr9hL15TunscTh_g0IEu6CzqugofTROoNU/edit

**Comment by Ravenstine** [comment]
The last step to this ticket is verifying whether or not broadcast content is being successfully pushed to the PMP in production.  Staging/sandbox is one thing.  Production is often another. ;)

**Comment by vsinghkpcc** [comment]
I think there's a significant amount of effort represented against this ticket. Let's close for now and re-open or open a different ticket as needed for verification.
