### ISSUE TITLE
Short List body copy text is invisible

### ISSUE THREAD

**Issue by chris-fuller** [SCPR/SCPRv4#458]
This issue is occurring in the iPhone app, but since it's the display of a webpage, we are creating the issue here in SCPRv4.

This issue only occurs when viewing the Short List for the first time, meaning after iPhone app installation (or re-installation).

Also, the body copy text is only invisible for a minute. After a a short time the body copy text is fine.

Also note that I was able to reproduce this issue approximately 3 times, but not consistently.

![slack for ios upload png](https://cloud.githubusercontent.com/assets/16296673/13652088/2ea5f1ea-e5ff-11e5-9f16-dcd834230ae0.jpeg)
![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/16296673/13652092/331c87ca-e5ff-11e5-9468-2598f3ad46eb.jpeg)
![slack for ios upload-2 png](https://cloud.githubusercontent.com/assets/16296673/13652095/3564ae22-e5ff-11e5-8146-20c014f287c2.jpeg)

**Comment by sdillingham** [comment]
@chris-fuller my suspicion is that this issue should be filed in the KPCC-iPhone repo. This font rendering issue only ever occurs inside our iPhone app, and the app has a fair amount of code in SCPRShortListViewController that tries to understand and manipulate the state of the web view. I'd look there first to see if we might be doing something that could be preventing the font from loading before we start looking for issues in SCPRv4

**Comment by Ravenstine** [comment]
This has been addressed in the iPhone app.
