### ISSUE TITLE
OtherPrograms importer is importing duplicate episodes

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#468]
See the current state of these shows for examples:

http://www.scpr.org/programs/latino-usa/
http://www.scpr.org/programs/radiolab/
http://www.scpr.org/programs/fresh-air/

This has happened before - our program importer job somehow imports episodes twice. The AC would be to:

1. Clean up all duplicate episodes in the DB
2. Investigate whether the importer can be improved to prevent these kinds of dupes

**Comment by sdillingham** [comment]
Looks like the problem with duplicate external programs is still a thing:

http://www.scpr.org/programs/this-american-life/

**Comment by Ravenstine** [comment]
This was patched a while ago.  Though the solution wasn't pretty, it has prevented duplicates for some time now, so I'm removing this from the backlog.
