### ISSUE TITLE
Add MoGo GTM - Remove old Pixel

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#473]
AC

- [x] MoGo GTM code is added to scpr.org.
- [x] Old MoGo pixel is removed from scpr.org.

**Comment by sdillingham** [comment]
Here's the spot in our code where we currently have a GTM tracking tag:

https://github.com/SCPR/SCPRv4/blob/master/app/views/shared/footer/_tracking_scripts.html.erb#L63-L69

**Comment by sdillingham** [comment]
Also for reference (from the GTM docs):
https://support.google.com/tagassistant/answer/3207128?hl=en#multiple_tags

**Comment by vsinghkpcc** [comment]
GTM code sent via Slack.
