### ISSUE TITLE
Set up our servers to run `npm install` on deployment

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#474]
#459 

Now that we have a package management system for our external JS libraries, we need to figure out how we are going to deploy SCPRv4 with this change.  Right now, we don't have our servers set up to install/update vendor JS packages on each deploy so, while we can run locally and use CircleCI, pushing this work to staging and production fails.  This may mean digging in to Deploybot/Capistrano.  IDK yet.

AC: Figure out how we are triggering things like `bundle install` on deployment and add installment of NPM packages to that strategy.

**Comment by Ravenstine** [comment]
@sdillingham 
There are a couple of options that I see so far.  The simplest would be to add a rake task to SCPRv4 that gets triggered before `deploy:updated`, which is also the same stage where Capistrano runs `bundle install`.  The advantage I see here is that we wouldn't have to touch Deploybot.

Alternatively, adding `require "capistrano/npm"` to Rails deploys in Deploybot would also work.  Though it would attempt this on every Rails deploy.  Not sure that's really a good thing.

I kind of lean towards the first solution.  What sounds good to you?

**Comment by Ravenstine** [comment]
Actually, it also looks like we could add a cap file like this one:
https://github.com/capistrano/bundler/blob/master/lib/capistrano/tasks/hooks.cap

But a Rake file should also work, like this example:
https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/migrations.rake

**Comment by sdillingham** [comment]
I agree that the first option is better; let's go with a rake task.

**Comment by Ravenstine** [comment]
Seems I was mistaken about the first assumption; Capistrano runs tasks with before/after hooks if it's included inside a project, but Deploybot is including Capistrano as a library and it will currently only run the tasks that it is set up to:
https://github.com/SCPR/Deploybot/blob/master/lib/deploybot/run_deploy.rb

So I do think that, at some point, there will probably need to be some code included in the process that will check the project directory for `package.json`

**Comment by Ravenstine** [comment]
Seems I was mistaken about the first assumption; Capistrano runs tasks with before/after hooks if it's included inside a project, but Deploybot is including Capistrano as a library and it will only run the tasks that it is set up to:
https://github.com/SCPR/Deploybot/blob/master/lib/deploybot/run_deploy.rb

So I do think that, at some point, the next preferred solution would be to include code in Deploybot that runs a custom task file in any Rails project that is deployed.  

Maybe something like this: 
```ruby
case @deploy.app.app_type
when "rails"
  begin; require "#{fetch(:deploy_to)}/lib/capistrano/rails"; rescue LoadError; end
  require "capistrano/rails"
  SSHKit.config.command_map[:rake] = "bundle exec rake"
  ...
```
This is currently hard to test out without running an actual deploy.  I have an instance of Deploybot running locally, but I haven't got it to a point where I can run an actual deploy.

Less-desirable, to me anyway, would be to include code that will check the project directory for `package.json` and then require 'capistrano/npm' if present.

**Comment by Ravenstine** [comment]
@sdillingham This is currently on staging.  The changes to Deploybot are in production.  Any feedback is welcome.

**Comment by sdillingham** [comment]
Any chance you can resolve the related content errors on article views on staging? I'd like to do some functional QA on those pages.

**Comment by Ravenstine** [comment]
@sdillingham Ah yes, I've been meaning to look into that.  Since I don't know how to pull a fresh DB into staging, I'll probably patch Article.  After I take a quick look at the Adtech problem, I'll check this out and let you know.

**Comment by Ravenstine** [comment]
I should have closed this ticket a while ago, as Deploybot can now deploy Rails projects that also have a package.json file.
