### ISSUE TITLE
Morning Edition external program not updating

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#482]
In production, the Morning Edition external program hasn't updated since Tuesday. Need to investigate why the `sync_external_programs` job is failing on this show.

**Comment by Ravenstine** [comment]
I have been looking at this and my initial poking didn't reveal any problem.  Running the sync then downloaded the episode for that day.  I was wondering if it was a fluke in the feed, but it looks like it still isn't pulling in new episodes, so this will be one of my tasks today.

**Comment by Ravenstine** [comment]
UPDATE: Looks like something in the response from All Things Considered is causing a `TypeError: no implicit conversion of String into Integer` with our NPR gem.  Looks like I'm going to have to attempt to modify that gem or at least see what response it is getting.
