### ISSUE TITLE
Investigate: Why are we firing our adcount pixel twice on Listen Live?

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#484]
For history, see this conversation in slack: https://kpcc.slack.com/archives/ad-ops/p1459878016000002

AdTech responded: https://kpcc.slack.com/archives/ad-ops/p1459895907000018

AC: Identify the cause of the AdCount pixel firing twice on Listen Live.

**Comment by Ravenstine** [comment]
Fixed in commit [630deae745238bd5e44f9fbf7fba75a60400c417](https://github.com/SCPR/SCPRv4/commit/630deae745238bd5e44f9fbf7fba75a60400c417).
