### ISSUE TITLE
Set up new logic to index / reindex the homepage beta

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#488]
AC: The homepage beta is reindexed whenever there's an update to the homepage beta

**Comment by Ravenstine** [comment]
Indexing to ElasticSearch is handled in this new library:
https://github.com/SCPR/SCPRv4/blob/better_homepage/lib/home_base.rb

The BetterHomepage model has callbacks that asynchronously call this library under certain conditions:
https://github.com/SCPR/SCPRv4/blob/better_homepage/app/models/better_homepage.rb

When the indexed version of a homepage is requested, it then grabs all the articles from the articles index in one call to ContentBase.
