### ISSUE TITLE
Logic for computing the most specific Label

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#491]
AC
- [x] If the story is a KPCC In Person Event, use the label “KPCC In Person"
- [x] Otherwise, the most specific label is applied to articles as available in the order of Keyword, Program, Series, then Beat

Question: Where do we compute this? On the homepage index? When the article is saved?

**Comment by Ravenstine** [comment]
I'm in favor of computing the value on homepage index since we aren't using it elsewhere at this point.  The method generating the value can just as easily be moved to the article methods concern if we need the label elsewhere in the future.

**Comment by sdillingham** [comment]
Agreed @Ravenstine.

**Comment by sdillingham** [comment]
@Ravenstine - taking a quick look at the code where you're computing the label:

https://github.com/SCPR/SCPRv4/blob/a6de41af61478c7918886a47bec837cf49633868/app/models/homepage_content.rb#L35-L45

What would the label method return if, for example, a piece of content is a event _and_ has a keyword tag of "immigration"?

Also, I think Vijay and I missed an AC for this ticket: I believe this label should return the content's Category as a final fallback if no other value is present.

**Comment by Ravenstine** [comment]
@sdillingham If it is a KPCC In Person event, it will always return "KPCC In Person".  If the event was not a KPCC In Person event, it would choose the keyword "Immigration".

Sure, I can work in the category.

**Comment by Ravenstine** [comment]
This is the current logic for computing the label:
```ruby
      return "KPCC In Person" if content.try(:is_kpcc_event)
      tags = (content.try(:tags) || [])
      (
        tags.find{|t| t.try(:tag_type).try(:include?, 'Keyword')} ||  # keyword
        content.try(:show) ||                                         # program
        tags.find{|t| t.try(:tag_type).try(:include?, 'Series')} ||   # series
        tags.find{|t| t.try(:tag_type).try(:include?, 'Beat')} ||     # beat
        content.try(:category)                                        # category
      ).try(:title)
```

It's functionally the same as the first version, except it adds the category as the final fallback.  Closing for now.
