### ISSUE TITLE
Manage Asset Scheme for each story

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#494]
AC: An Editor can control if each homepage Story displays none, medium, or full image

**Comment by Ravenstine** [comment]
Handled in logic here:
https://github.com/SCPR/SCPRv4/blob/better_homepage/app/assets/javascripts/outpost/homepage/application.js.coffee

Which inherits front-end logic from here:
https://github.com/SCPR/SCPRv4/blob/better_homepage/app/assets/javascripts/framework.js.coffee
