### ISSUE TITLE
Check It Out Management

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#495]
AC
- [x] An Editor can add a maximum of five links in the Check It Out area
- [x] The Editor can write a custom label per link

**Comment by Ravenstine** [comment]
The work in this branch, while still needing to be integrated into the homepage beta ticket, essentially does the job.
https://github.com/SCPR/SCPRv4/compare/better_homepage...better_homepage_check_it_out?expand=1

**Comment by sdillingham** [comment]
I agree with the decision to reuse our related related links feature here - makes good sense given the use case. We'll just need to be sure to code our views to defend against the possibility that no related links exist for a homepage.

**Comment by Ravenstine** [comment]
@sdillingham Yeah, so maybe we want to require a minimum amount of links before the Check It Out element appears?

**Comment by sdillingham** [comment]
Eh, I think if there's even one link there we need to render it. But if there's zero related links then we should hide the entire Check it Out component on the homepage.

**Comment by Ravenstine** [comment]
👍
