### ISSUE TITLE
Summary Fields on Articles

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#497]
AC
- [x] There are abstract fields on articles that populate the homepage beta summary content area on the front-end
- [x] There is a fallback to the teaser, in case there is no abstract is submitted.

**Comment by vsinghkpcc** [comment]
Reviewed with EZ this morning, he's good with the plan - only point to mention is that we should call these "abstracts".

Other questions we still need to answer:
What formatting will we support?
Do we fall back to teaser when a summary is not available?

**Comment by sdillingham** [comment]
Answers to your questions @vsinghkpcc (also relevant for @Ravenstine):

### Formatting

We should support paragraphs, unordered lists, and bold formatting. We can add other formatting as needed down the road, but to start these two options should be sufficient.

### Fallbacks

we definitely need to support a fallback to a teaser when an abstract isn't available. We should use the same callback approach we currently use to generate teasers on publish:

https://github.com/SCPR/SCPRv4/blob/7715f971dea12b413cdaa42fcc69bb8177b4a93a/app/concerns/concern/callbacks/generate_teaser_callback.rb

**Comment by Ravenstine** [comment]
I updated the AC to reflect the current criteria and status.  What I have left to do is add the fallback.
