### ISSUE TITLE
Image loading for performance

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#502]
AC
- [ ] Implement responsive images
- [ ] Evaluate if there is a quick win, lazy loading solution

**Comment by sdillingham** [comment]
I doubt I will be able to get to this in Sprint 34 or 35, so I'm going to un-assign myself from this issue.

**Comment by sdillingham** [comment]
@Ravenstine opened https://github.com/SCPR/SCPRv4/issues/651, which essentially duplicates this issue. Closing.
