### ISSUE TITLE
beta opt in/out UI + set cookie

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#505]
AC
- [x] There is a way to message to users that they can opt in to the beta
- [x] There is a way for opted-in users to opt out
- [x] When a user has opted in, they will be delivered to the beta whenever they visit scpr.org / kpcc.org

**Comment by Ravenstine** [comment]
The controller switch triggered by the cookie is set in the routes using constraints:
```ruby
  get '/' => 'home#index', constraints: lambda { |request| !request.cookie_jar[:beta_opt_in]}, as: :root
  get '/' => 'better_homepage#index', constraints: lambda { |request| request.cookie_jar[:beta_opt_in]}
```

The opt-in button on the classic homepage is simply this:

```html
<button class='btn btn-primary' id="beta-opt-in">Try Our New Homepage</button>
<script>
  $('#beta-opt-in').on("click", function(){
    document.cookie = "beta_opt_in=true";
    location.reload();
  });
</script>
```

The opt-out button is virtually the same but removes the cookie.

The work is on staging and placed in the `better_homepage` branch.  The layout used for the new homepage was ripped off the homepage testing tool, so it's not current.
