### ISSUE TITLE
Site-wide frontend issue: Uncaught TypeError: this.time.strftime is not a function

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#521]
Not sure when/how this issue was introduced onto the site, but we're currently seeing the following javascript error across the site:

`Uncaught` TypeError: this.time.strftime is not a function`

Javascript is breaking on this function and causing a lot of other JS on the site to break (for example, sharing links on articles aren't working).

**Comment by Ravenstine** [comment]
Solved in: #523
