### ISSUE TITLE
Homepage: implement nav from style guide

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#529]
AC
- [x] The nav is implemented
- [x] The nav bar is wired up to display the currently airing program

**Comment by Ravenstine** [comment]
The nav bar has been implemented, but there is an issue with the icons coming and going, so I am leaving this as in-progress.

**Comment by Ravenstine** [comment]
I'm actually going to close this because, while related, the icon issue is tangental.
