### ISSUE TITLE
Elections Support for June Primary: Homepage results

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#531]
AC
- [x] There is a solution to display Chris Kellers elections results numbers on Tuesday, June 7th.
    * URL to static html with homepage results will be: http://162.243.135.6/static/results/featured.html
    * URL to static html with all results will be: http://162.243.135.6/static/results/all.html
- [x] There is a solution to remove the elections results numbers on Wednesday, June 8th.

**Comment by sdillingham** [comment]
FYI: the election results component should be added to the homepage layout here:

https://github.com/SCPR/SCPRv4/blob/master/app/views/layouts/homepage.html.erb#L97
