### ISSUE TITLE
Homepage Beta: Analytics Audit

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#546]
AC
- [x] The scroll depth of the Beta and Current homepage are confirmed to be aligned for comparison
- [ ] There is a clear list of any additional events to track
- [ ] Those events are impelemented

**Comment by Ravenstine** [comment]
@sdillingham 
Here's what I'm tracking:

- Scroll depth
- Article clickthroughs w/ scroll depth
- Related Content clickthroughs
- Donate button click
- Check It Out clickthroughs
- Call to Action clicks

Anything else?

**Comment by sdillingham** [comment]
Until we have Hidden Gems implemented, I think this list covers all our bases @Ravenstine. @vsinghkpcc do you agree?

**Comment by vsinghkpcc** [comment]
Yep - looks good to me!
