### ISSUE TITLE
Ordering of items in Outpost aggregator prioritizes events content too much 

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#549]
AC
- [ ] An Editor isn't overloaded with events before seeing recent news stories in Outpost aggregator

In Outpost models where Events are included in aggregator collections and items are ordered by `public_datetime`, upcoming Events are always front-loaded at the top of the list because we map `public_datetime` to the `starts_at` time of the Event. 

The result is that producers will consistently have to page through 1-2 dozen upcoming Events before they can see the most recently published articles, which is inefficient and slows down their work. Curating Events into an aggregator is almost always a secondary use case - it's far more common for producers to need to grab a NewsStory, ShowSegment or BlogEntry with a recent `published_at` timestamp. 

We map `public_datetime` to `Event.starts_at` here:

https://github.com/SCPR/SCPRv4/blob/master/app/models/event.rb#L189

In general this mapping is the right choice, and other parts of our code (our public API, for example) depend on this mapping. But in a specific case like Outpost aggregation, where we're trying to order a collection of content models based on their recency, Events shouldn't be sorted based on a `starts_at` date that's usually in the future. 
 
We need a way inside our [private API articles endpoint](https://github.com/SCPR/SCPRv4/blob/master/app/controllers/api/private/v2/articles_controller.rb) to order Events by their `updated_at` attribute while allowing other content models to continue to be ordered by `public_datetime`.

**Comment by Ravenstine** [comment]
Awesome idea, @sdillingham.

**Comment by Ravenstine** [comment]
I doubt that I'm going to complete this in the next hour and a half, so I'll just mention that this is almost definitely going to require modifying the Elasticsearch query in ContentBase to support conditional or script based sorting.  I have to take time to figure out and test how to do this with Elasticsearch.

**Comment by Ravenstine** [comment]
For now, I'm going to work on omitting events from the main results for the aggregator, but if we were to enable scripting, this is essentially the script that would do better sorting:

```ruby
      sort: {
        _script: {
          script: "if(doc['_type'].value=='Event'){ return doc['updated_at'].value;} else { return doc['public_datetime'].value; };",
          type: 'number',
          order: 'desc'
        }
      },
```
