### ISSUE TITLE
Add Tagline to Politics Vertical footer

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#560]
AC
- [x] The copy "No rant, no slant" appears in the footer of the politics landing page in place of "89.1 KUOR 90.3 KVLA"

**Comment by Ravenstine** [comment]
@vsinghkpcc kpcc My guess is that the politics page is sharing a footer template with other pages.  To be clear, do we only want this tagline to show up on the politics page and no other pages, or all pages with that footer?

**Comment by vsinghkpcc** [comment]
Let's limit to just the politics page, thanks!
