### ISSUE TITLE
Styling of tables in Outpost

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#575]
Call it a pet peeve, but digital producers regularly go into stories to add "width='100%'" styling to our tables in Outpost, knowing that it will be wiped off as extraneous code in the next save. Is it possible to style tables to fill the frame of story? It can look very awkward otherwise. Thanks. 

ex:
http://www.scpr.org/news/2016/07/05/62337/riverside-county-gets-1st-confirmed-case-of-zika-v/

**Comment by chrislkeller** [comment]
My two cents: Seems like giving ```table.kpcc-table``` a 100% width like we've done [here](http://projects.scpr.org/internal/tools/spreadsheet-to-table-converter/) would solve the issue?

cc @ezass, @sdillingham

**Comment by sdillingham** [comment]
Probably correct @chrislkeller. If you have time to make that change in SCPRv4 and issue a pull request, @ravenstine could merge and deploy.

**Comment by Ravenstine** [comment]
@ezass I've added 100% width to the kpcc-table class.  Let me know what you think.

**Comment by chrislkeller** [comment]
Thanks @Ravenstine.... Looks like the css on the page was set for ```.report .kpcc-table``` tables...

    .report .kpcc-table {
        border-top: 3px solid #f17b21;
        border-bottom: 3px solid black;
        width: 100%
    }

**Comment by ezass** [comment]
Thanks, y'all comrades.
