### ISSUE TITLE
FB Instant & Apple News

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#581]
AC
- [x] Create and configure our account for FB Instant
- [x] Create and configure our account for Apple News
- [ ] Implement current RSS feed solution and review results

History: https://github.com/SCPR/digital_products/issues/33

**Comment by Ravenstine** [comment]
Update: Production articles submitted to Facebook for approval.  It says it should take 3-5 business days.  After that, we should be able to begin publishing.

**Comment by Ravenstine** [comment]
Update: Facebook finally got back, but articles can't be published because there's some sort of style issue that has to be worked out.  Unfortunately, they were not terribly specific.

KPCC is now in Apple News, along with a logo and cover thumbnail.  A few adjustments need to be worked out with certain elements in the feed, but it is otherwise acceptable for now.

**Comment by Ravenstine** [comment]
Update: Facebook articles resubmitted for review.

**Comment by Ravenstine** [comment]
UPDATE: Apple news articles have been corrected somewhat, though there's still an issue with it not pulling in the lead assets for the stories.  I'm not sure why that is as I think my opengraph meta tags are correct, so I put a bounty on an [SO question](https://stackoverflow.com/questions/34059454/what-does-apple-news-use-to-determine-when-images-are-displayed) that asked about the same problem but got no responses.  The bodies of the apple news stories should be cleaner than they were, and soon the correct bylines should come in on future stories.

**Comment by Ravenstine** [comment]
Currently investigating using the News Publisher API and whether or not it's work using their nonfree Ruby API client.

**Comment by vsinghkpcc** [comment]
Moving progress on this effort here: https://github.com/SCPR/digital_products/issues/103
