### ISSUE TITLE
Most Commented module is displaying outdated/incorrect content

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#589]
The Most Discussed section of the site is display stories from over the weekend that are no longer current/correct:

![0](https://cloud.githubusercontent.com/assets/442483/16963964/dadac65a-4dad-11e6-8ed9-168a0d7e5e02.jpg)

(You can view a live example of this module on many 2013-era pages on the site, e.g.: http://www.scpr.org/programs/ (in the sidebar)

This could be due to some aspect of a job failing, or the cache not being updated properly.

Relevant code is here:

https://github.com/SCPR/SCPRv4/blob/7715f971dea12b413cdaa42fcc69bb8177b4a93a/app/jobs/job/most_commented.rb

If you log into the Disqus API console (credentials in Meldium), you can construct the query and see what is currently being returned: https://disqus.com/api/console/.

**Comment by sdillingham** [comment]
This issue appears to have resolved itself(?)

**Comment by Ravenstine** [comment]
Yeah, it seems fine to me.  I'll still periodically check it, in case there's still some kind of fluke happening.

**Comment by Ravenstine** [comment]
Still seems fine to me.
