### ISSUE TITLE
Clean up Twitter Card meta tags

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#595]
AC

- [ ] The twitter card pulls the article description, only defaulting to the generic site description when there is no article description

Example: https://twitter.com/KPCC/status/755894372877545472

view-source:http://www.scpr.org/programs/take-two/2016/07/20/50631/the-life-and-legacy-of-garry-marshall/

Note that the Twitter tags appear twice, and the tag lower in the source is pulling the generic site description

**Comment by chrislkeller** [comment]
For the future, would love to see recognition of audio on a page and populate twitter tags to activate the [audio player card](https://dev.twitter.com/cards/types/player)...

**Comment by sdillingham** [comment]
@chrislkeller based on your understanding of Twitter's spec, would serving our content over SSL be a requirement to support audio cards?

**Comment by Ravenstine** [comment]
This wasn't successful, apparently.  Will re-attempt this next sprint.

**Comment by chrislkeller** [comment]
@sdillingham: the ```twitter:image```, ```twitter:player``` and ```twitter:player:stream``` values/URLs need to point to https:// paths...
