### ISSUE TITLE
Apple News API

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#614]

**Comment by Ravenstine** [comment]
Just want to make sure I don't forget where this was:
https://developer.apple.com/library/ios/documentation/General/Conceptual/iAd_News_Advertising/SettingUpYourContent.html#//apple_ref/doc/uid/TP40016664-CH4-SW7

(describes setting up ads, which exist both outside the content and within it as components)

**Comment by Ravenstine** [comment]
The next two tickets should probably be about deploying the Apple News code and the other one integrating Ads into the content stream.
