### ISSUE TITLE
Embedly video function doesn't appear to work

### ISSUE THREAD

**Issue by ezass** [SCPR/SCPRv4#622]
Youtube videos emdedded with the embedly funciton don't appear to show in the published story. Several reporters and shows have mentioned this to us. Brian and I have been advising them to embed using Youtube's code instead. 

![screen shot 2016-08-22 at 11 58 17 am](https://cloud.githubusercontent.com/assets/994636/17867611/0546fc70-6860-11e6-861b-b442461b6128.png)
![screen shot 2016-08-22 at 11 58 45 am](https://cloud.githubusercontent.com/assets/994636/17867616/0fa7a494-6860-11e6-9f6b-80a7acbc5b0f.png)

**Comment by sdillingham** [comment]
This issue was reported last week, and @Ravenstine is looking into it, so I'm assigning this issue to him so we can track associated work here.
