### ISSUE TITLE
Homepage Beta: Backend Prep

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#628]
~~(HOLD ON THIS TICKET UNTIL COMPLETE RULES ARE OUTLINED)~~

AC
 There is a backend solution for managing
- [ ] Latest Headlines
- [ ] Topic Clusters
- [ ] How someone on broadcast would promote something on the website, and where it would live

- [ ] The frontend solution proves that this all works (doesn't need to be final design)

**Comment by Ravenstine** [comment]
@sdillingham @vsinghkpcc Have these rules been outlined yet?  Or do we need to set up some time to flesh them out?

**Comment by sdillingham** [comment]
@Ravenstine the rules have been outlined in https://github.com/SCPR/design/issues/173. When you're ready to work on this ticket, just review the notes in that issue and then let's sit down and discuss how to break this down into work items.
