### ISSUE TITLE
Write a Dockerfile

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#631]
Writing a Dockerfile for SCPRv4, in order to build Docker images, would likely solve many of the issues with getting the app up and running on a machine.  Instead of installing several dependencies manually, running SCPRv4 locally would only be a matter of installing Docker and then executing the Dockerfile.  This would also be a good idea because the server environment could be closely replicated on the Docker machine, therefore reducing the possibility of edge cases, rare they may be, caused by differences in dependency/library versions.  Of course SCPRv4 could continue to be run without the Dockerfile.

**Comment by Ravenstine** [comment]
All the more reason to explore Dockerizing SCPRv4:
https://circleci.com/docs/docker/

**Comment by Ravenstine** [comment]
On inter-container communication(e.g. SCPRv4 & mysql backups):
https://stackoverflow.com/questions/30545023/how-to-communicate-between-docker-containers-via-hostname

**Comment by nakedsushi** [comment]
Synctree put this on their roadmap to be worked on in 3-4 works, so no need for us to do anything. It's part of the work they'll be doing to make the app horizontally scalable. Basically, they'll have a docker-compose manifest that will pull down the relevant images to get SCPRv4 running, and have helper scripts that will get us a snapshot of the production database to use for development.

**Comment by Ravenstine** [comment]
👍
