### ISSUE TITLE
Make images lazy-load on homepage

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#651]
I thought I made a ticket for this already, but I can't find it.

I think it would be a good idea to make the images on the homepage lazy-load, or download as the user scrolls downward.  Our images can be relatively large and can slow things down significantly on mobile.  Making them load as-needed and somewhat progressively would provide a better mobile experience, as seen on our AMP pages where this is already happening.

**Comment by Ravenstine** [comment]
Gonna store some ideas on what library to use here:

- [bLazy](http://dinbror.dk/blazy/?ref=blog)
- [lazySizes](https://afarkas.github.io/lazysizes/)

**Comment by Ravenstine** [comment]
Just some notes so far:

- No matter what, the page still loads relatively fast on good bandwidth.
- On slow bandwidth, the biggest offenders are:
  - Trying to load too many large images at once. (of course)
  - Listen live tile (1400x1400 image doesn't need to be loaded on mobile especially with a crappy connection)
  - TypeKit fonts (several requests made)
  - Hidden gems (background image)
  - Some of the analytics scripts.
  - Application javascript loads at least 1mb of data.  This was more necessary back when we had more living content on our page, but we may want to reconsider this if we are only keeping the status indicator for stories.  (I kinda think we should just eliminate that, but that's just my opinion)


So far, doing the following has shown improvement in loading/usability:
- Using bLazy makes it so that assets are only loaded as needed.  In other words, images will only be requested as the user scrolls down the page.  On a fast connection, this is not noticeable.  On a slow connection, the user currently sees a grey placeholder where the asset eventually gets loaded.  bLazy detects the device screen size and only loads large resolution images on big screens, and small images on small screens.
- Removing hidden gems helps out slightly.  Because we are using background images, I can't simply plug bLazy into it like I could with Listen Live, so this will require more work to make lazy-load.
- I was able to remove a few javascript dependencies we no longer need but managed to stick around.
- Changing the order in which scripts are loaded has improved things somewhat.  (not the application script is only requested after the main DOM content has been received.
- Disabling the tracking scripts does improve load time, but I haven't investigated into whether or not there's a way we can restructure the scripts.  It may be worth looking at whether or not Google AMP provides a more lightweight way to support things like GA, Mixpanel, Chartbeat, etc.

**Comment by nakedsushi** [comment]
@Ravenstine I wouldn't worry about TypeKit since it looks like we've enabled longer cache times for the font kits, which in theory should just be loaded from the cache after initial load. I don't see any additional requests to TypeKit after reloading kpcc.org a few times so I'm guessing the cache is working.

**Comment by Ravenstine** [comment]
@nakedsushi Yeah, it's just an initial load thing, and there's probably not much we can do about it anyway.  Just kinda stinks having to load like 6+ woff files. (why when we have maybe 2 or 3 fonts, idk)

**Comment by Ravenstine** [comment]
Not going to get to this, realistically.
