### ISSUE TITLE
FB Instant Article Metrics

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#675]
~~AC: We're tracking unique users, page views, and any other low hanging metrics we can from Facebook Instant Articles.~~

AC
- [ ] We're tracking basic stats in aggregate.

**Comment by Ravenstine** [comment]
Until this ticket gets moved into the pipeline, basic insights can be seen in the page manager:
https://www.facebook.com/kpcc/publishing_tools/?refSource=pages_manager_bar&section=INSTANT_ARTICLES

This includes unique views, time spent, and scroll depth for individual stories.  These metrics can only be seen on a single story level and not aggregate, sadly.

**Comment by Ravenstine** [comment]
I'm putting this ticket to rest for the time being as there is still some time needed to confirm that we are getting the tracking that we need.  Otherwise, work has been done to track page views & scroll depth.  Time spent should be tracked automatically.
