### ISSUE TITLE
Mailgun: Audit Domain Verification Changes

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#678]
Mailgun sent us some updates. Log into mailgun and see if we need to make any changes or verify any of our existing send domains:

--- email posted below ----
We’re writing to let you know of several upcoming changes that may impact your Mailgun account.  This email contains a list of steps that you can reference that will help you determine if you need to make any changes to your configuration to continue using the service.

On November 1st, 2016:

Any domain created from this date forward will require verification through the use of a DKIM and SPF record to send and receive messages.
On December 1st, 2016:

All domains, regardless of the creation date, will be required to verify the domain to continue sending and receiving messages.
All subdomains of mailgun.org will be treated as sandbox domains, which are domains that allow sending to a list of up to five authorized recipients.
Mailgun is making these changes to our verification system to provide an additional proof of ownership check. Over the last several years, we've gradually increased the verification requirements based on industry best practices to ensure optimal deliverability.  These changes mean that all domains on your account will be handled consistently regardless of when they were created.

You can determine if these changes impact your account by following the steps below:

Checking for Unverified Domains

Login to the Mailgun control panel and select the Domains section.
Select any domain that is in the orange "unverified" state.  
In the Domain Verification & DNS section, locate the records with the red warning indicator.
In the DNS administration tool provided by your DNS or hosting provider, add all records under the section "DNS Records for Sending".   We have guides available that describe this process for the most common providers.
After the records have been added, click the "Check DNS Records Now" button.   Due to caching, up to 24 hours may be required before Mailgun is able to resolve the newly created records.
Once verification has been completed successfully, your domain will switch to a "verified" state.
Checking Sandbox Domains

Login to the Mailgun control panel.
Check for domains listed under the "sandbox domains" header on the dashboard home page.
Ensure that your application is not relying on any of the listed sandbox domains for sending and receiving.  If sandbox domains are being used, you must create a sending domain by clicking the "Add Domain" button under the sending domains section.
Additionally, you can use the logs and reporting features of the Mailgun control panel to determine what domains are actively sending and receiving messages on your account.  If you need assistance making these changes, please reach out to our support team by creating a ticket here.

**Comment by Ravenstine** [comment]
LGTM
