### ISSUE TITLE
Checklist for making the beta the official homepage

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#689]
AC
- [x] We have a complete checklist of tasks for making the beta the official homepage

**Comment by Ravenstine** [comment]
I'm just going to put the checklist here and post it in Slack so we can refer to it later.

So here's the minimum of what we'd need to do:

- Change the root path in `routes.rb` to point to the BetterHomepages controller.
- Make `/beta-homepage` redirect to root.
- Remove markup for opt-in / opt-out boxes/buttons.
- Change the `/beta-opt-in` and `/beta-opt-out` paths to just redirect to root and no longer set a cookie.

First stage cleanup:
- Rename controller to HomeController.  This has no effect on anything, but it just sorta makes sense.
- Change the model name from BetterHomepage to Homepage and change the name of the better_homepages table. (both should happen at the same time)
- Remove BetterHomepages from Outpost and rename `views/outpost/better_homepages` to `views/outpost/better_homepages`.  That's all we would really need to do as Outpost already has a permission record for Homepages and would just treat the new model as the same thing.

Second stage cleanup:
- Remove old CSS around the classic homepage.  There's no single "home" style, so this should happen when we do site-wide style unification.
