### ISSUE TITLE
Empyrean: Standardize format

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#690]
AC
- [x] There is a standard format that works for all scpr.org content (articles, segments, blog posts, event pages)

**Comment by Ravenstine** [comment]
This is the article schema in its current form:
https://github.com/SCPR/grand-central/blob/master/schemae/article.yml

I've written it in a way that should be fairly future-proof and requires a minimum amount of custom properties per data type.  A few very distinct changes from our current article schema are the **location** and the **dateRange** properties which are there to support extra data around events, but are more generic as to support a possible future need of those concepts in other article types.
