### ISSUE TITLE
Investigate iHeartRadio HLS want

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#693]
AC

- [ ] iHeartRadio can access our HLS stream
- [x] iHeartRadio users do not get counted into our iPhone or Android users stats in StreamMachine dashboard

**Comment by nakedsushi** [comment]
@vsinghkpcc Can you pass along this URL to our HLS stream to Diane Flotten at APM.  She should configure iHeartRadio so that it uses this as our stream: `http://live.scpr.org/sg/kpcc-aac.m3u8?ua=iheartradio`

As long as iHeartRadio is requesting our stream with the url parameter `ua=iheartradio`, we should be able to see their listeners in our dashboard in the new 'iheartradio' line here http://ops-streamdash.scprdev.org/. You'll notice there's only 1-2 hits around 10:28 and 11:47 there, which is me testing my changes.  Once iHeartRadio starts using the new URL, we should be seeing more numbers there.

Since we don't currently separate 3rd party clients, I'm not sure how important it is to keep their client stats separate.  My plan is to have this running like this for a month, see if it's a significant number or not, and if it's not, just combine iHeartRadio back into 'others' like before.

**Comment by vsinghkpcc** [comment]
iHeartRadio is also asking for the stream URL to be HTTPS - getting the cert configured, if any effort falls to us, will be covered in a different ticket. I'll also manage getting the final stream link configured in iHeartRadio.
