### ISSUE TITLE
Add LI ad tags to Short List creation

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#705]
NOTE: we need the ad tags before work can begin.

AC
- [x] The Monday and Daily Short List use the new LI ad tags

**Comment by Ravenstine** [comment]
*waiting to hear back from APM on how they got both these ad tags and link tracking working*

**Comment by vsinghkpcc** [comment]
Currently blocked. Coordinating with APM to see if we can get these tags working with link tracking.

**Comment by vsinghkpcc** [comment]
Tags approved!
