### ISSUE TITLE
Update contact information on Outpost error page

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#717]
:point_up:

**Comment by vsinghkpcc** [comment]
@Ravenstine you're probably already thinking in this direction, but let's make this change as evergreen as we can, something like:

- [ ] contact info on 404 page is to a link to the slack #web-ops channel, and a mailto link to scprdev@scpr.org. (or some other evergreen solution)

**Comment by Ravenstine** [comment]
Agreed.

**Comment by Ravenstine** [comment]
Duplicate ticket.
