### ISSUE TITLE
Special Investigation Story Buildout

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#723]
AC
- [x] The story is implemented based on the final design
- [x] We have accommodated all edits
- [x] The story is ready for public consumption based on Editorial's deadline

Note: This assumes a basic approach to the additional functionality (rep. lookup and letter)

**Comment by tinykb** [comment]
### Other dev things not included in the final edits from EL:
- [ ] Share buttons at top and bottom of story no longer point to OIS content
- [ ] Bylines + credits should be linked to reporter page or staffer email address

### Some design tweaks to be addressed after final copy changes are made:
- [ ] H1 font size (Why more California families are becoming homeless) can be significantly smaller than it is now
- [ ] Smaller chart headings (23/26?), FranklinGothic URW Light
- [ ] Diamond-y line dividers should be equidistant from the bottom of the last graf and the top of the next one
- [ ] Button font = FranklinGothic URW across the board
- [ ] Plus sign in nav: #338B91
- [ ] Tighten up space between bullets under "Facts you may want to share"
- [ ] 2x-ify charts for small screens

**Comment by Ravenstine** [comment]
Repo here:
https://github.com/scpr/hsp
