### ISSUE TITLE
Investigate Reports of Homepage Issues

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#725]
AC
- [ ] ~~Find STR to break the homepage (i.e. blank homepage)~~
- [x] Deploy new homepage version that should address these reports

**Comment by Ravenstine** [comment]
Didn't get back to this, but getting back on implementing the new 3 column sass mixin should solve that particular issue.  I am not aware of us getting any new reports of that blank page problem, though.

**Comment by Ravenstine** [comment]
#739

Blank page issue is gone.
