### ISSUE TITLE
Clean up viewsLeft workaround for KPCC Plus stream

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#733]
In `listen_controller.rb`, we temporarily commented out some code that was breaking the pledge free stream for some users.  It was breaking because of an issue with parse-server not being able to update that user's row to decrement their `viewsLeft` attribute. That issue has been resolved.

AC
- [x] commented code is refactored so that it goes back to decrementing `viewsLeft` but can fail gracefully if `authorized_user.save` errors.

**Comment by Ravenstine** [comment]
[73086954be](https://github.com/SCPR/SCPRv4/commit/73086954be300e850ecc3f7091fe2b48991adce6)

Tested on staging.
