### ISSUE TITLE
Remove "Commenting Survey"

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#735]
AC
- [x] The survey mechanism has been removed from the site.

(The part that says "Help KPCC improve our comments section! Take a 5 minute survey")
![screen shot 2017-01-06 at 11 07 28 am](https://cloud.githubusercontent.com/assets/13337277/21729563/6ba08cb4-d400-11e6-9c06-32422d1c6092.png)

**Comment by Ravenstine** [comment]
Taken care of in this [commit](https://github.com/SCPR/SCPRv4/commit/171abf9f102652a2c51b71f428684b2b92f4c4fb).
