### ISSUE TITLE
Update Take Two Assets related to Programming Changes

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#741]
THIS TICKET SHOULD BE COMPLETED on 1/27/2017 AFTER TAKE TWO AIRS BUT BEFORE EOD

AC
- [x] Picture and description update in dropdown (description should start: Join A Martinez... etc)
- [x] Picture update on scpr.org/programs/ landing page
![screen shot 2017-01-27 at 11 40 49 am](https://cloud.githubusercontent.com/assets/13337277/22385012/c45b368e-e485-11e6-8608-443d89601a84.png)

- [x] Picture and description update on segment page right-rail. 
![screen shot 2017-01-27 at 11 44 06 am](https://cloud.githubusercontent.com/assets/13337277/22385058/faf08190-e485-11e6-8db4-085145b7a4c7.png)
(description should read the same as found on the KPCC Programs page description: Join Take Two each weekday at 9 AM where we’ll translate the day’s headlines for Southern California, making sense of the news and cultural events that people are talking about. Find us on 89.3 KPCC, hosted by A Martinez.)

See this ticket for designs: https://github.com/SCPR/design/issues/246

**Comment by Ravenstine** [comment]
OBJECTIVE COMPLETE

**Comment by vsinghkpcc** [comment]
![screen shot 2017-01-27 at 3 24 01 pm](https://cloud.githubusercontent.com/assets/13337277/22391185/a71a59d2-e4a4-11e6-8aad-88bd6c4728f3.png)

Looks like the dropdown menu still needs to be updated?

**Comment by vsinghkpcc** [comment]
Looks good now!
