### ISSUE TITLE
Update SCPRv4 codebase to https

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#763]
To prepare for the ideal state where everything is redirected to https, we'll need to go through the SCPRv4 code to make sure all generated URLs are https.

AC:
- [x] auto-generated URLs from Outpost are HTTPS
- [ ] ~~asset URLs are HTTPS~~
- [ ] ~~we don't get any mixed content warnings in the major browsers because we're requesting assets using a different protocol (https <=> http)~~

**Comment by Ravenstine** [comment]
This needs to be split out into a another ticket because assethost is returning HTTP urls even when using the HTTPS endpoint.  The amount of time spent patching the AssetHost library would be not much less than attempting to fix AssetHost itself.
