### ISSUE TITLE
AssetHost: Color code images that are OK to use

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#768]
Coordinate w/ Brian Frank to get a cheatsheet of what types of images are OK to use in an article and which ones are not (ie: ones imported from NPR articles).  Figure out a way to display this information in Outpost so that web producers and other people publishing stories get a warning when attaching images to their stories.

The biggest hurdle is getting assethost running on the development machine and getting changes deployed, but since that needs to be understood by the digital team anyway, it's good to do this.

AC:
- [ ] images that are questionable should be greyed out or have some other visual clue that makes it clear that the content creator should check with a web editor before publishing.

**Comment by vsinghkpcc** [comment]
Work on this ticket should be considered a part of the new AssetHost version.

**Comment by Ravenstine** [comment]
Got the implementation figured out.  Now I just need to ponder about how best this feature should be included.  It's very specialized and shouldn't be included in the "community edition" of AssetHost.  Could potentially be added as a more abstract feature, but that would require writing a custom config setup or a DSL, which isn't really worth the time investment at this point.  Thinking it could be a Rails plugin, but need to in general think more about how 3rd parties can add their own code while still being able to easily upgrade AssetHost versions.

**Comment by Ravenstine** [comment]
Putting this aside because the implementation has been mostly figured out, but needs to be applied by building a plugin; I think it would be better to make some headway on Alexa during the remainder of this sprint.
