### ISSUE TITLE
Fix Job::SyncExternalPrograms

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#769]
Open up the resque failed queue and look at any of the failed jobs that look like this:

```
Job::SyncExternalPrograms
Arguments
--- rss
...
Exception
OpenSSL::SSL::SSLError
```

AC:
- [ ] That job no longer shows up in the failed queue because it fails gracefully or is fixed.

**Comment by vsinghkpcc** [comment]
closing in favor of #766
