### ISSUE TITLE
Show landing pages' audio player missing context query parameter

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#785]
If you look at the main audio player in a episode landing page (http://www.scpr.org/programs/offramp/2017/03/11/15520/) when you click on it, you'll notice in your network traffic that it requests an mp3 like this:
https://media.scpr.org/audio/offramp/20170311_offramp.mp3?context=offramp&via=website&uuid=a08a341d-4529-4b6a-8b03-1d293fe9f098

The important parameter to look at is the 'context=offramp' query parameter.  This is correct.

If you look at the "Listen to Episode" player on the show landing page (http://www.scpr.org/programs/offramp/), when you click on the player and look at network traffic, it is missing that query parameter.  It should have one. I think this is happening for all of our show landing pages.

AC:
- [ ] show landing pages' audio player requests the mp3 with the correct context query parameter

**Comment by arellaTV** [comment]
@nakedsushi 

I think I managed to fix it!
- Uses helper function url_with_params to pass in parameters
- Uses the instance variable, @program.slug, to supply show's context value
- Also adds 'via: website' parameter, similar to the episode page
- Network tab shows the parameter context=offramp in both Off-Ramp's landing page and episode page

Does the landing pages' request also need the `via=website` parameter, just like the episode page has it?

**Comment by nakedsushi** [comment]
Sure, we might as well add that in too. Good catch.

**Comment by arellaTV** [comment]
- Had to resolve some dependency/ circle issues. Involved:
  - Adding new IP's to allow in Webmock 7b59ea8cb50a32427083fe845b1af7dea132ad97
  - Reverting to previously working Gemfile 826dbb73d81952cdd8a2bd0a92409149e05c8228
  - Nilchecking strip_inline_assets d432549d3d379446a99acb81cfd205496e267479
    - Returning the original body 9a97d5772f8e64694ab9106a46df37bb5468587f

My local copy is now inline with the exact dependencies as the previous successful build. I was able to get it to build successfully once with circle, but not more than once at a time. The tests were hanging intermittently. @nakedsushi allowed for more IPs in Webmock and did a nilcheck for the strip_inline_assets function that was hanging the build up.
