### ISSUE TITLE
Video feature on Homepage should say 'Video'

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#790]
When a NewsStory is a video (`news.feature.name === 'Video'`) there's no video button or special marker on it on the homepage like there is for Audio or Slideshows.

Here's how an 'Audio' featured NewsStory looks: <img width="829" alt="screen shot 2017-03-20 at 9 29 10 am" src="https://cloud.githubusercontent.com/assets/360040/24110048/af234caa-0d4f-11e7-8357-b2c4660281e4.png">

AC:
- [x] `_meta.html.erb` supports when `feature_name === 'Video'`
- [x] users on the homepage can see when a NewsStory has video

**Comment by arellaTV** [comment]
Feature confirmed to work in staging! Unconfirmed to work in production as there isn't a video featured news item on the homepage yet.
<img src='http://i.imgur.com/f2JcHFm.png' />
Can be found on this commit: https://github.com/SCPR/SCPRv4/commit/f1be89fd91e755c923fee5c0c2327b6b5c64ba20

**Comment by arellaTV** [comment]
Confirmed to work in production!

![Imgur](http://i.imgur.com/q9DU3LB.png)
