### ISSUE TITLE
Investigate Ads being cut off in Chrome and Firefox on Windows

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#791]
TIMEBOXED!!!

![image001](https://cloud.githubusercontent.com/assets/13337277/24210834/89ac40a0-0ee7-11e7-8c09-73cfb16daba6.jpg)

AC

- [x] Understand what's causing the ads to get cut off on desktop windows machines, chrome and firefox.
- [x] Pose some initial possible solutions.

**Comment by arellaTV** [comment]
Currently running into an issue with CircleCI build.
`Outpost::NewsStoriesController behaves like resource controller with proper permissions POST /create creates the resource - spec.controllers.outpost.news_stories_controller_spec
spec/controllers/outpost/news_stories_controller_spec.rb
moreexpected result to have changed by 1, but was changed by 0
Outpost::NewsStoriesController behaves like resource controller with proper permissions PUT /update updates the record - spec.controllers.outpost.news_stories_controller_spec
spec/controllers/outpost/news_stories_controller_spec.rb
moreexpected result to have changed, but is still Thu, 23 Mar 2017 15:38:57 PDT -07:00`

**Comment by vsinghkpcc** [comment]
@arellaTV I believe the browsers were chrome 57 and firefox 51.
