### ISSUE TITLE
Program Landing Page Leftovers

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/SCPRv4#796]
#775 :point_left: Addressing the leftovers of that ticket.

- [x] - Complete the program landing page prologue element.
- [x] - Add player UI to the featured story element.
- [x] - Attempt to vertically-align the footers in the featured-programs element.

**Comment by arellaTV** [comment]
------
- [ ] Responsiveness
- [ ] Verify that GA is intact

**Comment by arellaTV** [comment]
- Basic Responsiveness is implemented
- Google Analytics tracking mirrors deployed site

**Comment by arellaTV** [comment]
# Desktop Version
![Imgur](http://i.imgur.com/QNs6U7T.png)

# Mobile Version
![Imgur](http://i.imgur.com/a81CQOr.png)
