### ISSUE TITLE
Create List Resource

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#801]
iOS app needs the concept of lists, which are collections of arbitrary objects.  We'll need to create a new ActiveRecord model, an api endpoint, tests, and make it editable by Outpost users.

**Comment by Ravenstine** [comment]
What should these lists be comprised of?  Might it be something that could be accomplished with an Elasticsearch query?

For example, [this is an endpoint](https://github.com/SCPR/SCPRv4/blob/master/app/controllers/api/public/v3/programs_controller.rb#L34-L38) I added back in 2015.

And this is the main code in Contentbase:
https://github.com/SCPR/SCPRv4/blob/master/lib/content_base.rb#L95-L114

This is what makes the archive picker UI possible, as it queries the program and generates a tree of episodes by year/month.  If you need several lists of things in one response, an Elasticsearch aggregation may be more efficient.  But it depends on what you're querying... if it's not blogs;stories;segments;episodes;shells;pij;events, then this idea won't work.
