### ISSUE TITLE
Create List ActiveRecord model

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#802]
This new ActiveRecord model will be a list of different objects. For example, a list could hold Articles, Events, and Programs. It should act like the `MissedItBucket` model in that it can contain an ordered list of other objects.

A `list` object should have:
* starttime (datetime) default NULL
* endtime (datetime) default NULL
* context (string) default NULL
* position (integer)
* title (string)

AC:
- [ ] create the migration for a `lists` table
- [ ] create the ActiveRecord model
- [ ] List < ActiveRecord::Base validates that title is present
- [ ] run the migration for the `lists` table on staging
- [ ] run the migration for the `lists` table on production

**Comment by Ravenstine** [comment]
See https://github.com/SCPR/SCPRv4/pull/811
