### ISSUE TITLE
Create /list API endpoint

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#803]
This is for v3 of the API. 

The objects being returned from the list does not need to be all the attributes. Coordinate with @jeffc-kpcc to see exactly what attributes each type of object should include in the response. For example, for articles, we may only need to include a Headline.

AC:
- [ ] GET /lists should return all of the lists.
- [ ] GET /lists with `context` query param should only return lists with that context param.
- [ ] GET /lists/<list_id> should return all of the objects of that list (see note about objects above)
- [ ] If we're past the 'Start Time' and it's defined and 'End Time' is not, then the list should be live

**Comment by Ravenstine** [comment]
See https://github.com/SCPR/SCPRv4/pull/811
