### ISSUE TITLE
Add documentation for the exit modal

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#813]
AC:

- [x] Explains how to create a modal on outpost
- [x] Explains how to trigger the opening of the modal
- [x] Explains the priority of modals

**Comment by nakedsushi** [comment]
Did you think of a location to put this documentation? If it's not developer-heavy at all, what do you think of putting it in the wiki? https://github.com/SCPR/outpost/wiki

**Comment by arellaTV** [comment]
Documentation for the Exit Modal usage can be found here:
https://github.com/SCPR/outpost/wiki/Exit-Modals
