### ISSUE TITLE
Exit modal funkiness with a lot of text when viewed on mobile

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#817]
![image_uploaded_from_ios_480](https://cloud.githubusercontent.com/assets/13337277/25050391/13b17754-20fc-11e7-96f7-061c31d01a80.jpg)

AC

- [ ] The Exit Modal, when it has a lot of text, doesn't look broken when viewed on mobile

**Comment by arellaTV** [comment]
<img src='http://i.imgur.com/yGy4hQh.png' />
Latest commit 518840eae2d29385ebfef782f060c3a2477d411a updates modal to dynamically change height according to its inner contents. Now users can add as much content as they want. Tangentially, this commit also fixes a bug with h2 styling not being applied.
