### ISSUE TITLE
Change links to accommodate "Apple Podcasts" guidelines

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#818]
https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html

AC

- [x] Links on non story pages are swapped to meet the Apple guidelines.

Example: on /podcasts, the links should read "Subscribe to [the-show-name] on Apple Podcasts"

**Comment by Ravenstine** [comment]
https://github.com/SCPR/SCPRv4/pull/842
