### ISSUE TITLE
SCPR-Health-Dashboard: Discoverable Outside of Network

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#826]
AC:

- [x] Application can be accessed from networks outside of building

**Comment by nakedsushi** [comment]
Is there a specific IP that needs access? Right now the firewall only allows whitelisted IPs

**Comment by arellaTV** [comment]
@nakedsushi As of now, they're asking for access from anywhere

**Comment by nakedsushi** [comment]
http://healthcheck.scprdev.org/ should be accessible from everywhere now.
