### ISSUE TITLE
GA Event Tracking for Exit Modals

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#828]
AC
- [x] We can see how many impressions a specific message got (ex. The Frame vs. the default message vs. donation ask)
- [x] We can see how many conversions (form submit or CTA click) a specific message got

**Comment by arellaTV** [comment]
Now sends GA events for the following triggers:
- Open Modal
- Close Modal
- Subscribe (for Short List or Frame modals)
- Click (for Pledge Drive modals)

Each event includes a label with the following format:
`{Modal Type} | {URL} | {optional: Subscription}`

Example events:
Category: `Modal`
Action: `Open Modal`
Label: `Modal Type: The Frame Exit Modal | URL: http://localhost:3000/programs/the-frame/2017/02/18/55164/a-new-study-puts-some-numbers-to-hollywood-s-issue/`

Category: `Modal`
Action: `Subscribe`
Label: `Modal Type: The Frame Exit Modal | URL: http://localhost:3000/programs/the-frame/2017/02/18/55164/a-new-study-puts-some-numbers-to-hollywood-s-issue/ | Subscription: The Frame`

The result on Google Analytics looks like this:
<img src='http://i.imgur.com/Qr8IALT.png' />

**Comment by nakedsushi** [comment]
👍 Thanks for including the example events.
