### ISSUE TITLE
Investigate Amp Page Not Displaying All The Things

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#840]
Comparing the amp version (http://www.scpr.org/news/2017/04/20/70858/130-000-rides-thousands-of-routes-falling-winter-r.amp) and not amp version (http://www.scpr.org/news/2017/04/20/70858/130-000-rides-thousands-of-routes-falling-winter-r) of the page, you'll notice that the map embed, the table style, and bullets are not being shown in the amp version. Why is that?

AC:
- [x] we know why amp version looks so weird
- [x] if it's a quick fix, we fix it so amp version has embeds and the right styles for tables and bullets

Let's timebox this to a 0.5 and if it ends up being bigger, feel free to split the fixing into a separate ticket.

**Comment by arellaTV** [comment]
Having trouble with `amp-iframe` tag not accepting `src` with the `http://` protocol. I've abstracted finding a solution to that in another ticket: https://github.com/SCPR/SCPRv4/issues/852
