### ISSUE TITLE
Sort by date in Outpost after search

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#841]
AC

- [x] After performing a search in the outpost admin, the results are sortable by date

Example: http://www.scpr.org/outpost/remote_articles/search?button=&direction=DESC&order=published_at&query=American+Homefront&utf8=%E2%9C%93

**Comment by Ravenstine** [comment]
BAM!

https://github.com/SCPR/SCPRv4/pull/872
