### ISSUE TITLE
Change "Update Your Checking Account" Link in Nav

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#863]
AC

- [x] The "Update your Checking Account" link in the site nav links to: https://scprcontribute.publicradio.org/contribute.php?refId=EFTupdate

**Comment by arellaTV** [comment]
Changes are reflected in the following PR: https://github.com/SCPR/SCPRv4/pull/882

Will wait until Monday, July 3rd, to ship as to avoid any problems over the weekend.

**Comment by arellaTV** [comment]
The changes along with a quick bugfix in outpost/ circle ci is now shipped to production.
