### ISSUE TITLE
Aesthetic Unity: Archive and Search

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#867]
AC

- [x] Archive
- [x] Search Results
------
- [x] Responsiveness
- [x] Verify that GA is intact

Mockups: https://github.com/SCPR/design/issues/204

**Comment by arellaTV** [comment]
![Imgur](http://i.imgur.com/POCzV5H.png)
- One caveat that I found:
  - Because Google is populating the search contents, I can't separate the results by programs and posts as the mockups call for (within the scope of the ticket).

**Comment by arellaTV** [comment]
![Imgur](http://i.imgur.com/yTq5RxP.png)
![Imgur](http://i.imgur.com/gqKUDLi.png)
