### ISSUE TITLE
Aesthetic Unity - Categories

### ISSUE THREAD

**Issue by arellaTV** [SCPR/SCPRv4#879]
AC:

- [x] Work with Katie to find out which design to use
- [x] Category view has all necessary cells
- [x] Category view is responsive
- [x] Category view has GA tracking intact

**Comment by arellaTV** [comment]
![Imgur](http://i.imgur.com/53gU03P.png)

**Comment by arellaTV** [comment]
@tinykb 

I was able to salvage a lot more of the Vertical view than I thought! Here are the few things that are missing that are Vertical specific:
- The Resources cell
- The Featured Interactive cell
- The Featured Quote cell
- The Vertical Topics cell
- The Host List cell

The one feature that is in Categories that are not in Verticals
- The pagination feature

**Comment by arellaTV** [comment]
I worked with Katie on the next steps regarding this page. She comp'ed a new template really quick that's more stripped down. That mockup is below:

![Imgur](http://i.imgur.com/kBkb0G5.png)

**Comment by arellaTV** [comment]
@tinykb 

This is what the category page ended up looking like. Please let me know if anything stands out to you (or if anything is implemented incorrectly).

![Imgur](http://i.imgur.com/1qjlGr7.png)

**Comment by tinykb** [comment]
@arellaTV Looks good! There are a few details that are a little hinky, but I can pick those up when I get to the aesthetic unity nitpick ticket.

**Comment by arellaTV** [comment]
Okay, sounds good! Thanks @tinykb!
