### ISSUE TITLE
Update Short List CTA Supporting Copy

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#883]
The current copy reads: "Catch up each morning with KPCC's Short List newsletter."

AC: Change "morning" to "afternoon"

**Comment by arellaTV** [comment]
<img width="597" alt="screen shot 2017-07-27 at 12 58 16 pm" src="https://user-images.githubusercontent.com/16679701/28689700-5b4dd532-72cb-11e7-8c94-139e874b3036.png">

Updated wording now appears in production! Here's an example:
https://www.scpr.org/programs/take-two/2017/07/27/58230/two-proposed-laws-aim-to-close-the-gender-pay-gap/

Commit with the change: https://github.com/arellaTV/SCPRv4/commit/4c1db52e9615015ad94bab423155018c0bd0d87d
