### ISSUE TITLE
Include only news stories in Latest Headlines on Homepage

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#888]
AC

- [ ] The "Latest Headlines" on the homepage displays only news stories (i.e. exclude show segments, blogs, and events)

- [ ] Understand what it would take to make the below happen:

There is a desire to make sure there are no duplicates between the main content feed and Latest Headlines. What if an editor could include all stories in the main feed as they do now, but they would be hidden from the main feed (from the 3rd story down) until they fall out of the latest headlines.

So the "hierarchy" for determining where a story should appear: Main Content slot 1 > Main Content slot 2 > Latest Headlines > The rest of the main content feed.

**Comment by Ravenstine** [comment]
First AC addressed in [this commit](https://github.com/SCPR/SCPRv4/commit/bc5296292e9a7b0ee624f9e4ed00985835701cf2).

Second AC would be accomplished by changing `app/views/better_homepage/_contents.html.erb` to this:

```erb
<% @latest_stories = latest_stories(@homepage.content) %>

<% @homepage.content.each_with_index do |content, index| %>
  
  <% next if (index > 1) && @latest_stories.include?(content) %>

  <% source = content.content.try(:source)
    tag = if source != "KPCC" or source != 'kpcc'
              source
           elsif content.tags__title?
              content.tags__title
           elsif content.program?
              content.program
           elsif content.category__title?
              content.category__title
           end
  %>
  <article class="center hp-story <%= content.asset_scheme %>" style="order:<%= index %>;">
    <%= media_object content.asset_scheme, content: content, index: index, contents: @homepage.content %>
  </article>

<% end %>
```

So basically I've already implemented the second AC but I think it's still a question of whether or not we'd actually want to do that.  I feel like this could lead to a lot of confusion, so we'd need to definitely train people on this.
