### ISSUE TITLE
Eloqua Forms Transition

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#906]
AC

- [x] Forms (~10) supplied by APM to replace current Eloqua Forms are swapped out on scpr.org

Note: This is blocked until APM supplies the forms

**Comment by arellaTV** [comment]
Had a conversation with @vsinghkpcc and devs at St. Paul today.
Current workflow is:
- They send us the markup
- I implement the markup on staging
- They test the whether the form is working correctly

**Comment by arellaTV** [comment]
Newest replacement is up on production! http://www.scpr.org/news
Breaking news subscriptions are now set up with the new APM form. The rest of the forms will follow tomorrow.

**Comment by arellaTV** [comment]
Newest replacement for /contact is on production! http://www.scpr.org/contact

**Comment by arellaTV** [comment]
Deployed links for updated forms that are remaining:
- KPCC In Person: http://www.scpr.org/events/2017/08/18/2391/grand-performances-cameron-graves/
- The Short List: http://www.scpr.org/news/2017/08/07/74427/san-bernardino-man-suspected-of-arson-in-series-of/
- The Frame: http://www.scpr.org/programs/the-frame/2017/08/07/58418/in-good-time-robert-pattinson-transforms-into-a-to/ (broken destination landing page)
- SCPR Underwriting Production Form: https://mpr.tfaforms.net/35
- SCPR CFF Contact Form: http://www.scpr.org/events/forum/about
- SCPR Business Benefits Sign Up: http://www.scpr.org/support/benefits-business-signup/ (missing fields)
- SCPR CFF Proposed Event Form: http://www.scpr.org/events/forum/space/request/ (missing fields)

Awaiting links:
- SCPR Online Auction Donation
- SCPR Content Permissions Request Form
- SCPR Sustainer Conversion Form V2

**Comment by arellaTV** [comment]
Actually, this ticket appears to be larger than expected, because there are currently a few bugs in the deployed forms that they're starting to catch. They're updating the markup, and I'll be updating them as I receive them.

**Comment by arellaTV** [comment]
Deployed links for updated forms:

Breaking News: http://www.scpr.org/news
Contact: http://www.scpr.org/contact
KPCC In Person: http://www.scpr.org/events/2017/08/18/2391/grand-performances-cameron-graves/
The Short List: http://www.scpr.org/news/2017/08/07/74427/san-bernardino-man-suspected-of-arson-in-series-of/
The Frame: http://www.scpr.org/programs/the-frame/2017/08/07/58418/in-good-time-robert-pattinson-transforms-into-a-to/
SCPR Underwriting Production Form: https://mpr.tfaforms.net/35
SCPR CFF Contact Form: http://www.scpr.org/events/forum/about
SCPR Business Benefits Sign Up: http://www.scpr.org/support/benefits-business-signup/
SCPR CFF Proposed Event Form: http://www.scpr.org/events/forum/space/request/
SCPR Content Permissions Request Form: http://www.scpr.org/terms/request

Currently in Progress:

SCPR Online Auction Donation
SCPR Sustainer Conversion Form V2: http://www.scpr.org/support/sustainer

**Comment by arellaTV** [comment]
Deployed links for updated forms:

Breaking News: http://www.scpr.org/news
Contact: http://www.scpr.org/contact
KPCC In Person: http://www.scpr.org/events/2017/08/18/2391/grand-performances-cameron-graves/
The Short List: http://www.scpr.org/news/2017/08/07/74427/san-bernardino-man-suspected-of-arson-in-series-of/
The Frame: http://www.scpr.org/programs/the-frame/2017/08/07/58418/in-good-time-robert-pattinson-transforms-into-a-to/
SCPR Underwriting Production Form: https://mpr.tfaforms.net/35
SCPR CFF Contact Form: http://www.scpr.org/events/forum/about
SCPR Business Benefits Sign Up: http://www.scpr.org/support/benefits-business-signup/
SCPR CFF Proposed Event Form: http://www.scpr.org/events/forum/space/request/
SCPR Content Permissions Request Form: http://www.scpr.org/terms/request
SCPR Sustainer Conversion Form V2: http://www.scpr.org/support/sustainer

Discontinued:
SCPR Online Auction Donation

**Comment by arellaTV** [comment]
Seems like there is an issue with the confirmation landing page for the KPCC In Person sign-up. They're looking into it now.

**Comment by arellaTV** [comment]
KPCC In Person sign-up works!

Everything appears to be working. I'll keep an eye on it.
