### ISSUE TITLE
Update Disqus for ad free

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#914]
The problem: Disqus on our site is displaying ads and shouldn't be.

NOTES FROM NPR-DS:
Looking at your Disqus implementation, I see that www.scpr.org is actually not calling the NPR Disqus Javascript. On www.scpr.org, the Disqus file that is being referenced is https://kpcc.disqus.com/embed.js. However, in order to get the ad-free version of Disqus, www.scpr.org should call https://npr-kpcc.disqus.com/embed.js and use the following API Key: [Vijay will DM you this in slack]

AC
- [ ] Determine if we can make this change and retain all current comments on our site.
- [ ] make sure to use the https version of the embed, even if we don't end up using NPR disquis javascript

If Yes:
- [ ] Disqus on our site does not display ads
- [ ] Everyone who administrates Disqus still has the same access to administrate after this change is on production

If No:
- [ ] Review next steps with Vijay

**Comment by nakedsushi** [comment]
@vsinghkpcc can this be closed?
