### ISSUE TITLE
Research: Retain Ability to Edit Facebook Posts

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#915]
FB is trying to cut down on fake news and clickbait but limiting who can edit titles/headlines of stories posted to FB. Coordinate w/ Melissa's team so that:

AC:
- [ ] Document how any updated headlines made from outpost would still update the FB post

refs:
https://media.fb.com/2017/07/18/next-steps-to-addressing-link-preview-modification/
![screen shot 2017-07-31 at 2 21 53 pm](https://user-images.githubusercontent.com/360040/28799575-037c2332-75fe-11e7-9a09-c6196cca46d9.png)

**Comment by arellaTV** [comment]
- Updates link previews on new shares
- Doesn't update existing previews automatically
- You can edit previews before posting a link to facebook as KPCC
