### ISSUE TITLE
Automated Newsletters solution to support transition to SFMC Tweaks

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#921]
AC

- [x] For The Short List, the automated output uses the new SFMC Live Intent Ad Tags. (ask Vijay for the Tags)
- [x] Strip out any UTM code included in the HTML output (for both the Short List and Breaking News Alerts)

**Comment by vsinghkpcc** [comment]
- [ ] For the Short List Editions HTML preview output, replace 300x50 ad code table on line ~58 with:
`<table border="0" cellpadding="0" cellspacing="0" ><tr><td colspan="2"><a style="display: block; width: 300px; height: 50px;" href="http://li.scpr.org/click?s=216556&sz=300x50&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" rel="nofollow"><img src="http://li.scpr.org/imp?s=216556&sz=300x50&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" border="0" width="300" height="50"/></a></td></tr><tr style="display:block; height:1px; line-height:1px;"><td><img src="http://li.scpr.org/imp?s=216557&sz=1x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" height="1" width="10" /></td><td><img src="http://li.scpr.org/imp?s=216558&sz=1x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" height="1" width="10" /></td></tr><tr><td align="left"><a href="http://li.scpr.org/click?s=216544&sz=116x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" rel="nofollow"><img src="http://li.scpr.org/imp?s=216544&sz=116x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" border="0"/></a></td><td align="right"><a href="http://li.scpr.org/click?s=216545&sz=69x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" rel="nofollow"><img src="http://li.scpr.org/imp?s=216545&sz=69x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" border="0"/></a></td></tr></table>`

- [ ] Replace 300x250 ad code table on line ~183 with:
<table border="0" cellpadding="0" cellspacing="0" ><tr><td colspan="2"><a style="display: block; width: 300px; height: 250px;" href="http://li.scpr.org/click?s=216553&sz=300x250&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" rel="nofollow"><img src="http://li.scpr.org/imp?s=216553&sz=300x250&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" border="0" width="300" height="250"/></a></td></tr><tr style="display:block; height:1px; line-height:1px;"><td><img src="http://li.scpr.org/imp?s=216554&sz=1x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" height="1" width="10" /></td><td><img src="http://li.scpr.org/imp?s=216555&sz=1x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" height="1" width="10" /></td></tr><tr><td align="left"><a href="http://li.scpr.org/click?s=216544&sz=116x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" rel="nofollow"><img src="http://li.scpr.org/imp?s=216544&sz=116x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" border="0"/></a></td><td align="right"><a href="http://li.scpr.org/click?s=216545&sz=69x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" rel="nofollow"><img src="http://li.scpr.org/imp?s=216545&sz=69x15&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" border="0"/></a></td></tr></table>

- [ ] Replace RTB ad code table on line ~463 with:
<table cellpadding="0" cellspacing="0" border="0" width="40" height="6"><tbody><tr><td><img src="http://li.scpr.org/imp?s=124679000&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679001&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679002&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679003&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679004&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679005&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679006&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679007&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679008&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679009&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679010&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679011&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679012&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679013&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679014&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679015&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679016&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679017&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679018&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td><td><img src="http://li.scpr.org/imp?s=124679019&sz=2x1&li={LIST_ID}&e=%%emailaddr%%&p=%%jobid%%" width="2" height="6" border="0" /></td></tr></tbody></table>

- [ ] For both the Short List and Breaking News Alerts HTML preview, make sure UTM code is no longer appended to URLs. 
example: `href="http://www.scpr.org/programs/take-two/2017/08/10/58507/bluefin-tuna-won-t-be-listed-as-endangered-what-s/?utm_source=kpcc&utm_medium=email&utm_campaign=short-list?elqTrack=true` should be `href="http://www.scpr.org/programs/take-two/2017/08/10/58507/bluefin-tuna-won-t-be-listed-as-endangered-what-s/`

**Comment by nakedsushi** [comment]
Pending code review: https://github.com/SCPR/SCPRv4/pull/934

**Comment by nakedsushi** [comment]
https://github.com/SCPR/SCPRv4/commit/01aded68e1500ff082e0f46aea3da6f6479fd841

**Comment by nakedsushi** [comment]
Pushed to production. @vsinghkpcc can you check it out and if it looks good, go ahead and close this issue.
