### ISSUE TITLE
Fix HTTPS mixed content w/ Campaigns API

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#922]
This is blocked on the cert being fixed on scprdev.org.  You'll be able to tell the cert is fixed when you go to https://campaigns.scprdev.org/ and it doesn't show a roadblock about an error in certs.

AC:
- [x] we're using the https version of the campaigns API 
- [x] we don't see mixed content warnings for that endpoint when visiting https://www.scpr.org/

probably this file: https://github.com/SCPR/SCPRv4/blob/08c0f4ebccf7d8342e2af274e3c0c7f6d78490bf/app/assets/javascripts/visual_campaign.js.coffee

**Comment by nakedsushi** [comment]
https://campaigns.scprdev.org/ has been fixed, so this ticket is unblocked now.

**Comment by arellaTV** [comment]
Changes merged and shipped to production! https://scpr.org
