### ISSUE TITLE
Hide "Latest" Stories from Main Homepage Content Stream

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#940]
AC

- [x] Unless in position 1 or 2 in the main content stream, hide stories included by editors from displaying to end users until the story no longer is in the "Latest Headlines" section. (History and implementation help here: https://github.com/SCPR/SCPRv4/issues/888#issuecomment-319445700)

- [x] Include helper text in Outpost for a person editing the homepage `All stories in the “Latest Headlines” section will be hidden from the main content stream until it drops off. Exception: Stories in position 1 or 2. `

**Comment by Ravenstine** [comment]
deploy'd
