### ISSUE TITLE
HTTPS version of Member Benefits Card Broken

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#967]
http://www.scpr.org/support/member_benefits_card/ works because it loads the http iframe of the map.

https://www.scpr.org/support/member_benefits_card/ does not work because it's loading an http iframe and that is mixed content and a no-no.

Unfortunately, the company we're using to do the map does *not* have an https site: http://benefits.tayamo.co/index.php?cid=1

We have two options to fix it:

1.) contact tayamo and see how likely they are to set up an https version of the map
2.) we manually only link to the `http` version of the member benefits card and change all links to that page to http.

In the meantime, I fixed it in a hacky way by creating a new flatpage and redirecting all traffic from the previous url `/support/member_benefits_card` => `https://www.scpr.org/support/member_benefit_card`

AC:
- [x] clicking on member benefits card shows the map

**Comment by vsinghkpcc** [comment]
I've reached out to Tayamo, waiting to hear back on an estimate / timeline. If it's not reasonable, then we'll go with option 2.

**Comment by vsinghkpcc** [comment]
The iFrame is now HTTPS, so I think we can now enforce the HTTPS for https://www.scpr.org/support/member_benefit_card

**Comment by nakedsushi** [comment]
I removed the redirect so everything should now link to this version:

https://www.scpr.org/support/member_benefits_card/
