### ISSUE TITLE
Outpost: Featuring a video no longer works

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#982]
Steps to reproduce:

1. Create a news story in outpost
2. Add a video asset in the pop up asset chooser: https://www.youtube.com/watch?time_continue=1&v=GSDmqLQmMN0
3. In "Asset Display" dropdown, choose "Video"
4. Save and then view live
5. BUG: Instead of the video being in the featured section, it's some blown up screen cap of the video. Brian Frank said it used to display the video.

AC:
- [x] featuring a video shows the video in the featured spot
- [x] notify Brian once this is fixed

**Comment by Ravenstine** [comment]
Fixed.  Turns out the version of Rails being used in the legacy version of AssetHost wasn't adding digests to javascript file names.  Plus I changed the pre-compilation directory from `/assets` to `/resources` to avoid conflicts.  So there were multiple factors involved.
