### ISSUE TITLE
Remove old program in aesthetic unity

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#984]
AC
- [x] Remove "Off-ramp" from the nav menu (programs >> featured programs)
- [x] Remove "Off-ramp" from the KPCC PROGRAMS list on the top of the programs landing page

**Comment by vsinghkpcc** [comment]
Aha - didn't realize that was the case - thanks for the explanation! I've un-featured it on staging and production, but yeah let's keep this ticket as a reminder when we push to production.

**Comment by arellaTV** [comment]
Actually scratch that! Homepage nav still has outpost hardcoded >__<. But the main navigation and program page are now updated correctly. I'll log this as a bug for the homepage nav.

**Comment by arellaTV** [comment]
Fixed the homepage nav to auto-populate based off of what is featured in outpost

**Comment by arellaTV** [comment]
https://scprv4-staging.scprdev.org/
