### ISSUE TITLE
Include "Morning Edition" and "ATC" in featured programs 

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#985]
AC

- [x] Change the header on programs landing page from "KPCC Programs" to "Featured Programs"
- [x] Ensure that non-KPCC programs like ME and ATC get included in the nav menu and Featured Programs section of the Programs landing page when the "Featured" option is checked in Outpost
- [x] For the Quad Featured Programs CTA on the bottom of Program Landing pages, ideally leave out non-KPCC programs, otherwise change the heading (i.e. other featured programs > other KPCC programs)

**Comment by arellaTV** [comment]
- Added a column, `is_featured`, to external programs and made them editable in the External Program page of Outpost
- When selected, it will appear in the homepage nav menu, interior nav menu, and Program List page
- One Caveat is that we need images for both ME and ATC before we turn it on in prod

**Comment by arellaTV** [comment]
Example: https://scprv4-staging.scprdev.org/programs
