### ISSUE TITLE
Updates for KPCC In Person Landing Page

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#986]
AC
If an event is in the "highlighted events" list on the top of the in person landing page and today's date is after the event's ending date, change the date label:
- [x] No calendar icon
- [x] font color should be gray
- [x] label should read: *Past Event*

For the events listing section
- [x] If the event is set to "all day event" then don't display the start time (i.e. only display the date of the event)
- [x] Default the page to the "in person" section (alternatively / also have modify the order listed "in person"-"all events"-"sponsored events")

**Comment by arellaTV** [comment]
Updates are live on staging: https://scprv4-staging.scprdev.org/events/kpcc-in-person

**Comment by arellaTV** [comment]
All day events don't show the end time in the highlighted events, but they still show in the tabs in the middle of the page
- [ ] All event lists should follow the same rule where end times are avoided when the event is an all day event

**Comment by arellaTV** [comment]
Updated! https://scprv4-staging.scprdev.org/events/kpcc-in-person
- If the event is set to "all day event" then don't display the start time (i.e. only display the date of the event)
- Middle section should also be updated now, including all the other instances I could think of (e.g. https://scprv4-staging.scprdev.org/events/kpcc-in-person/archive)
