### ISSUE TITLE
Make related_content more performant

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#987]
The app spends a long time in the `cwidgets/_related_links.html.erb` partial due to finding all the related links for the content.  It's a pretty expensive DB call, so let's see if we can either make it less expensive, or at least put a 30 min cache on it.

I started with caching the view in the commits starting here as a quick fix: https://github.com/SCPR/SCPRv4/commit/02399a1d5fa86e4c0eaec43679d4632ed5e92507

But it's probably better to cache by the content object that's calling related_content.  Once we do that, we can get rid of the cache on the view layer: `<%= cache(["related_links", content.original_object, "v1"], expires_in: 30.minutes) do %>`

AC:
- [ ] related_links partial doesn't do a ton of DB calls every time

**Comment by vsinghkpcc** [comment]
cwidgets no longer being used, closing this ticket.
