### ISSUE TITLE
Get rid of `json_escape` monkeypatch

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/SCPRv4#992]
https://github.com/SCPR/SCPRv4/blob/3d96c33b86990fcad282bf3ca249c4e4b681619b/config/initializers/json_escape.rb

The comment up there leads me to believe we no longer need the monkeypatch.  Remove the monkey patch and see if things are still working.

AC:
- [ ] we got rid of `json_escape.rb` monkeypatch

**Comment by arellaTV** [comment]
AC:
- [x] `json_escape` is removed from initializers
- [x] branch passes tests
- [x] branch is pushed to staging
- [ ] each template type is tested on staging with no new errors showing up
- [ ] staging is tested over the course of a couple of days

**Comment by arellaTV** [comment]
I'm going to keep this in its own branch for now until the feature freeze ends on the 28th. Tested throughout the weekend with no apparent side effects
